IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='CTRL')BEGIN
    DECLARE @CTRL NVARCHAR(MAX);
    SET @CTRL=N'CREATE SCHEMA CTRL AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @CTRL;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='AMS')BEGIN
    DECLARE @AMS NVARCHAR(MAX);
    SET @AMS=N'CREATE SCHEMA AMS AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @AMS;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='FIN')BEGIN
    DECLARE @FIN NVARCHAR(MAX);
    SET @FIN=N'CREATE SCHEMA FIN AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @FIN;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='INV')BEGIN
    DECLARE @INV NVARCHAR(MAX);
    SET @INV=N'CREATE SCHEMA INV AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @INV;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='AUD')BEGIN
    DECLARE @AUD NVARCHAR(MAX);
    SET @AUD=N'CREATE SCHEMA AUD AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @AUD;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='HOS')BEGIN
    DECLARE @HOS NVARCHAR(MAX);
    SET @HOS=N'CREATE SCHEMA HOS AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @HOS;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='HR')BEGIN
    DECLARE @HR NVARCHAR(MAX);
    SET @HR=N'CREATE SCHEMA HR AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @HR;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='TVIEW')BEGIN
    DECLARE @TVIEW NVARCHAR(MAX);
    SET @TVIEW=N'CREATE SCHEMA TVIEW AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @TVIEW;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='VM')BEGIN
    DECLARE @VM NVARCHAR(MAX);
    SET @VM=N'CREATE SCHEMA VM AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @VM;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='CRM')BEGIN
    DECLARE @CRM NVARCHAR(MAX);
    SET @CRM=N'CREATE SCHEMA CRM AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @CRM;
END;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='REP')BEGIN
    DECLARE @REP NVARCHAR(MAX);
    SET @REP=N'CREATE SCHEMA REP AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @REP;
END;
