
TRUNCATE TABLE AMS.DllPrintDesigList
INSERT INTO AMS.DllPrintDesigList(ListId, Module, DesignDesc)
VALUES(1, 'SB', 'A4 Half PAN'),
	  (2, 'SB', 'Sales A4 Half'),
	  (3, 'SB', 'Sales A4 HalfPAN'),
	  (4, 'SB', 'Sales A5'),
	  (5, 'SB', 'Sales A5 PAN'),
	  (6, 'SB', 'Sales Invoice'),
	  (7, 'SB', 'Sales Invoice FNB'),
	  (8, 'SB', 'FNB Invoice 3inch'),
	  (9, 'SB', 'TaxInvoice3inch'),
	  (10, 'SB', 'TaxInvoice5inch'),
	  (11, 'SB', 'Invoice3inch'),
	  (12, 'SB', 'DefaultInvoice'),
	  (13, 'SB', 'DefaultInvoiceWithNotes'),
	  (14, 'SB', 'DefaultInvoiceWithVAT'),
	  (15, 'SB', 'MorselDesignWithVAT'),
	  (16, 'SB', 'BanepaMiniMart'),
	  (17, 'SB', 'BhabSagarSalesInvoice'),
	  (18, 'SB', 'DefaultInvoiceWithPAN'),
	  (19, 'SB', 'RestaurantDesignWithPAN'),
	  (20, 'SB', 'RestaurantDesignWithVAT'),
	  (21, 'SB', 'RestaurantDesignWithVAT5Inch'),
	  (22, 'SB', 'RestaurantDesignWithPAN5Inch'),
	  (23, 'SB', 'DefaultInvoiceWithVATWithOutNotes'),
	  (24, 'SB', 'AbbreviatedTaxInvoice3inch'),
	  (25, 'SB', 'AbbreviatedTaxInvoice3inchWithPreview'),
	  (26, 'SR', 'PrintDefaultReturnInvoice'),
	  (27, 'SR', 'DefaultReturnInvoiceWithVAT'),
	  (28, 'SR', 'AbbreviatedTaxReturnInvoice3inch'),
	  (29, 'SR', 'DefaultReturnInvoiceWithVAT'),
	  (30, 'SO', 'DefaultOrder'),
	  (31, 'SO', 'KOT/BOT'),
	  (32, 'SO', 'KOT/BOT RePrint'),
	  (33, 'DC', 'DayClosing'),
	  (34, 'SB', 'A4 Full'),
	  (35, 'SB', 'A4 Half'),
	  (36, 'SB', 'A5 Full'),
	  (37, 'SB', 'A5 Full'),
	  (38, 'SO', 'A4 Full'),
	  (39, 'SO', 'A4 Half'),
	  (40, 'SO', 'A5 Full'),
	  (41, 'PO', 'A4 Full'),
	  (42, 'PO', 'A4 Half'),
	  (43, 'PO', 'A5 Full'),
	  (44, 'PC', 'A4 Full'),
	  (45, 'PC', 'A4 Half'),
	  (46, 'PC', 'A5 Full'),
	  (47, 'PB', 'A4 Full'),
	  (48, 'PB', 'A4 Half'),
	  (49, 'PB', 'A5 Full'),
	  (50, 'PR', 'A4 Full'),
	  (51, 'PR', 'A4 Half'),
	  (52, 'PR', 'A5 Full'),
	  (53, 'PAB', 'A4 Full'),
	  (54, 'PAB', 'A4 Half'),
	  (55, 'PAB', 'A5 Full'),
	  (56, 'SC', 'A4 Full'),
	  (57, 'SC', 'A4 Half'),
	  (58, 'SC', 'A5 Full'),
	  (59, 'SC', 'A4 Full'),
	  (60, 'SC', 'A4 Half'),
	  (61, 'SC', 'A5 Full');;