using System;

namespace DatabaseModule.Print.SalesInvoice;

public class PrintingSalesInvoiceMaster
{
    public string VoucherNo { get; set; }
    public string VoucherDate { get; set; }
    public string VoucherMiti { get; set; }
    public DateTime VoucherTime { get; set; }
    public string RefVoucherNo { get; set; }
    public DateTime? RefVoucherDate { get; set; }
    public string RefVoucherMiti { get; set; }
    public long LedgerId { get; set; }
    public string LedgerDesc { get; set; }
    public string LedgerNepaliDesc { get; set; }
    public string LedgerPanNo { get; set; }
    public string LedgerAddress { get; set; }
    public long? PartyLedgerId { get; set; }
    public string PartyLedgerDesc { get; set; }
    public string PartyPanNo { get; set; }
    public string InvoicePartyName { get; set; }
    public string InvoicePartyPanNo { get; set; }
    public string PartyContactPerson { get; set; }
    public string PartyMobileNo { get; set; }
    public string PartyAddress { get; set; }
    public string InvoiceChequeNo { get; set; }
    public DateTime? InvoiceChequeDate { get; set; }
    public string InvoiceChequeMiti { get; set; }
    public string InvoiceType { get; set; }
    public string InvoiceMode { get; set; }
    public string InvoicePaymentMode { get; set; }
    public int DueDays { get; set; }
    public DateTime? DueDate { get; set; }
    public int? Agent_Id { get; set; }
    public string SalesMan { get; set; }
    public string SalesManCode { get; set; }
    public int? Subledger_Id { get; set; }
    public string SubLedger { get; set; }
    public string SubLedgerCode { get; set; }
    public string OrderVoucherNo { get; set; }
    public DateTime? OrderVoucherDate { get; set; }
    public string ChallanVoucherNo { get; set; }
    public DateTime? ChallanVoucherDate { get; set; }
    public int? DepartmentId { get; set; }
    public string Department { get; set; }
    public string DepartmentCode { get; set; }
    public int? CounterId { get; set; }
    public string CounterName { get; set; }
    public string CounterCode { get; set; }
    public int Cur_Id { get; set; }
    public string Currency { get; set; }
    public string CurrencySymbol { get; set; }
    public decimal InvoiceCurrencyRate { get; set; }
    public decimal TotalBasicAmount { get; set; }
    public decimal NetTermAmount { get; set; }
    public decimal TotalNetAmount { get; set; }
    public decimal TotalLocalNetAmount { get; set; }
    public decimal InvoiceVatAmount { get; set; }
    public decimal InvoiceTaxableAmount { get; set; }
    public decimal InvoiceTenderAmount { get; set; }
    public decimal InvoiceReturnInvoice { get; set; }
    public string InvoiceActionTag { get; set; }
    public string NumberInWords { get; set; }
    public string Remarks { get; set; }
    public bool IsReverse { get; set; }
    public string InvoiceCancelBy { get; set; }
    public DateTime? InvoiceCancelDate { get; set; }
    public string InvoiceCancelRemarks { get; set; }
    public bool IsPrinted { get; set; }
    public int NoOfPrint { get; set; }
    public string PrintedBy { get; set; }
    public DateTime? PrintedDate { get; set; }
    public string EnterBy { get; set; }
    public DateTime EnterDate { get; set; }
    public int? DoctorId { get; set; }
    public string DoctorName { get; set; }
    public string DoctorShortName { get; set; }
    public long? PatientId { get; set; }
    public string PatientLedger { get; set; }
    public int? HDepartmentId { get; set; }
    public string HospitalDepartment { get; set; }
    public string HospitalDepartmentCode { get; set; }
    public int? MShipId { get; set; }
    public string MShipDesc { get; set; }
    public int? MemberId { get; set; }
    public int? TableId { get; set; }
    public string TableName { get; set; }
    public string TableCode { get; set; }
}