using System;
using System.Windows.Forms;

namespace MrDAL.Core.Extensions;

public static class GuidExt
{// RETURN VALUE IN GUID
    public static Guid GetGuid(this string value)
    {
        Guid.TryParse(value, out var result);
        if (result == Guid.Empty)
        {
            result = Guid.NewGuid();
        }
        return result;
    }
    public static Guid GetGuid(this object value)
    {
        return value == null ? Guid.Empty : GetGuid(value.ToString());
    }
    public static Guid GetGuid(this TextBox value)
    {
        return value == null ? Guid.Empty : GetGuid(value.Text);
    }
    public static Guid GuidFromDateTime(this DateTime time)
    {
        var dateTime = DateTime.Now; // Replace with your DateTime value

        // Convert DateTime to a byte array
        var dateTimeBytes = BitConverter.GetBytes(dateTime.ToBinary());

        // Generate a byte array based on the components of the DateTime byte array
        var guidBytes = new byte[16];
        Array.Copy(dateTimeBytes, guidBytes, 8); // Copy the first 8 bytes of the DateTime byte array

        // Create a Guid from the generated byte array
        var guid = new Guid(guidBytes);
        return guid;
    }
    public static Guid GuidFromLong(this long value)
    {
        var guidData = new byte[16];
        Array.Copy(BitConverter.GetBytes(value), guidData, 8);
        return new Guid(guidData);
    }
}