using System;

namespace PrintControl.PrintClass.SalesInvoice;

public class SbDetails
{
    public string VOUCHER_NO { get; set; }
    public int VOUCHER_SNO { get; set; }
    public long PRODUCT_ID { get; set; }
    public string PRODUCT_DESC { get; set; }
    public string PRODUCT_ALIAS { get; set; }
    public string PRODUCT_SHORTNAME { get; set; }
    public string PRODUCT_TYPE { get; set; }
    public string PRODUCT_CATEGORY { get; set; }
    public int? PRODUCT_UNIT_ID { get; set; }
    public string UNIT_CODE { get; set; }
    public string UNIT_DESC { get; set; }
    public int? PRODUCT_ALT_UNIT_ID { get; set; }
    public string ALT_UNIT_CODE { get; set; }
    public string ALT_UNIT_DESC { get; set; }
    public string PRODUCT_VAL_TECH { get; set; }
    public decimal? PRODUCT_BUY_RATE { get; set; }
    public decimal? PRODUCT_SALES_RATE { get; set; }
    public decimal? PRODUCT_MARGIN_RATE { get; set; }
    public decimal? PRODUCT_TRADE_RATE { get; set; }
    public decimal? PRODUCT_MARGIN_2 { get; set; }
    public decimal? PRODUCT_MRP_RATE { get; set; }
    public int? PRODUCT_GROUP_ID { get; set; }
    public int? PRODUCT_SUB_GROUP_ID { get; set; }
    public decimal? PRODUCT_TAX_RATE { get; set; }
    public decimal? PRODUCT_MIN_STOCK_QTY { get; set; }
    public decimal? PRODUCT_MAX_STOCK_QTY { get; set; }
    public int? PRODUCT_DEPARTMENT_ID { get; set; }
    public string VEHICLE_CHASIS_NO { get; set; }
    public string VEHICLE_MODEL_NO { get; set; }
    public string VEHICLE_COLOR { get; set; }
    public string VEHICLE_ENGINE_NO { get; set; }
    public string VEHICLE_NUMBER { get; set; }
    public decimal? PRODUCT_BEFORE_BUY_RATE { get; set; }
    public decimal? PRODUCT_BEFORE_SALES_RATE { get; set; }
    public string PRODUCT_BARCODE { get; set; }
    public string PRODUCT_BARCODE_1 { get; set; }
    public string PRODUCT_BARCODE_2 { get; set; }
    public string PRODUCT_BARCODE_3 { get; set; }
    public int? GODOWN_ID { get; set; }
    public string GODOWN_DESC { get; set; }
    public string GODOWN_SHORTNAME { get; set; }
    public decimal ALT_QTY { get; set; }
    public int? ALT_UNIT_ID { get; set; }
    public string ALT_UOM { get; set; }
    public decimal QTY { get; set; }
    public int? UNIT_ID { get; set; }
    public string UOM { get; set; }
    public decimal INVOICE_RATE { get; set; }
    public decimal BASIC_AMOUNT { get; set; }
    public decimal TERM_AMOUNT { get; set; }
    public decimal NET_AMOUNT { get; set; }
    public decimal? ALT_STOCK_QTY { get; set; }
    public decimal? STOCK_QTY { get; set; }
    public string NARRATION { get; set; }
    public string ORDER_VOUCHER_NO { get; set; }
    public decimal? ODER_SNO { get; set; }
    public string CHALLAN_VOUCHER_NO { get; set; }
    public decimal? CHALLAN_SNO { get; set; }
    public decimal TAXABLE_AMOUNT { get; set; }
    public decimal VAT_AMOUNT { get; set; }
    public decimal TAX_RATE { get; set; }
    public int? FREE_QTY_UNIT_ID { get; set; }
    public decimal FREE_QTY { get; set; }
    public decimal STOCK_FREE_QTY { get; set; }
    public int? EXTRA_FREE_UNIT_ID { get; set; }
    public decimal EXTRA_FREE_QTY { get; set; }
    public decimal EXTRA_STOCK_FREE_QTY { get; set; }
    public bool? IS_TAXABLE { get; set; }
    public long? SALES_LEDGER_ID { get; set; }
    public long? SALES_RETURN_LEDGER_ID { get; set; }
    public string SIZE_1 { get; set; }
    public string SIZE_2 { get; set; }
    public string SIZE_3 { get; set; }
    public string SIZE_4 { get; set; }
    public string SIZE_5 { get; set; }
    public string SIZE_6 { get; set; }
    public string SIZE_7 { get; set; }
    public string SIZE_8 { get; set; }
    public string SIZE_9 { get; set; }
    public string SIZE_10 { get; set; }
    public string SERIAL_NO { get; set; }
    public string BATCH_NO { get; set; }
    public DateTime? EXPIRY_DATE { get; set; }
    public DateTime? MANUFACTURING_DATE { get; set; }
    public string IS_MATERIAL_POST { get; set; }
    public decimal DISCONT_RATE_ON_PRODUCT { get; set; }
    public decimal DISCOUNT_ON_PRODUCT { get; set; }
    public decimal BILL_DISCOUNT_RATE_ON_PRODUCT { get; set; }
    public decimal BILL_DISCOUNT_ON_PRODUCT { get; set; }
    public decimal SERVICE_CHARGE_RATE_ON_PRODUCT { get; set; }
    public decimal SERIVCE_CHARGE_ON_PRODUCT { get; set; }
}