using System;

namespace PrintControl.PrintClass.SalesInvoice;

public class SbExchangeDetails
{
    public string VOUCHER_NO { get; set; }
    public decimal VOUCHER_SNO { get; set; }
    public long PRODUCT_ID { get; set; }
    public string PRODUCT_DESC { get; set; }
    public string PRODUCT_ALIS { get; set; }
    public string PRODUCT_SHORTNAME { get; set; }
    public string PRODUCT_TYPE { get; set; }
    public string PRODUCT_CATEGORY { get; set; }
    public int? PRODUCT_UNIT { get; set; }
    public string PRODUCT_UNIT_DESC { get; set; }
    public string PRODUCT_UNIT_SHORTNAME { get; set; }
    public int? PRODUCT_UNIT_BR_ID { get; set; }
    public string PRO_BR_DESC { get; set; }
    public string PRO_BR_SHORTNAME { get; set; }
    public DateTime? PRO_BR_REG_DATE { get; set; }
    public string PRO_BR_ADD { get; set; }
    public string PRO_BR_COUNTRY { get; set; }
    public string PRO_BR_STATE { get; set; }
    public string PRO_BR_CITY { get; set; }
    public string PRO_BR_PHONENO { get; set; }
    public string PRO_BR_FAX { get; set; }
    public string PRO_BR_EMAIL { get; set; }
    public string PRO_BR_CT_PERSON { get; set; }
    public string PRO_BR_CT_PHONE { get; set; }
    public int? PRO_COMP_ID { get; set; }
    public string PRO_COMP_DESC { get; set; }
    public byte[] PRO_COMP_LOGO { get; set; }
    public DateTime? PRO_COMP_DATE { get; set; }
    public string PRO_COMP_ADDRESS { get; set; }
    public string PRO_COMP_COUNTRY { get; set; }
    public string PRO_COMP_STATE { get; set; }
    public string PRO_COMP_CITY { get; set; }
    public string PRO_COMP_PHONE_NO { get; set; }
    public string PRO_COMP_PAN_NO { get; set; }
    public string PRO_COMP_EMAIL { get; set; }
    public string PRO_COMP_WEBSITE { get; set; }
    public bool? PRO_COMP_STATUS { get; set; }
    public DateTime? PRO_COMP_CREATE_DATE { get; set; }
    public DateTime? PRO_COMP_LOGIN_DATE { get; set; }
    public string PRO_COMP_SOFT_MODULE { get; set; }
    public string ENTER_BY { get; set; }
    public DateTime? ENTER_DATE { get; set; }
    public bool? Status { get; set; }
    public int? PRODUCT_ALT_UNIT { get; set; }
    public string PRODUCT_ALT_UNIT_DESC { get; set; }
    public string PRODUCT_ALT_UNIT_SHORTNAME { get; set; }
    public int? PRODUCT_ALT_UNIT_BRANCH_ID { get; set; }
    public string PRO_ALT_UNT_BR_DESC { get; set; }
    public string PRO_ALT_UNT_BR_SHORTNAME { get; set; }
    public DateTime? PRO_ALT_UNT_BR_REG_DATE { get; set; }
    public string PRO_ALT_UNT_BR_ADDRESS { get; set; }
    public string PRO_ALT_UNT_BR_PHONE { get; set; }
    public string PRO_ALT_UNT_BR_EMAIL { get; set; }
    public string PRO_ALT_UNT_BR_CONTACT_PER { get; set; }
    public string PRO_ALT_UNT_BR_CONTACT_PER_DD { get; set; }
    public string PRO_ALT_UNT_BR_CONTACT_PER_PHONE { get; set; }
    public string PRO_ALT_UNT_BR_CRETD_BY { get; set; }
    public DateTime? PRO_ALT_UNT_BR_CRETD_DATE { get; set; }
    public string PRO_ALT_UNT_BR_MOD_BY { get; set; }
    public DateTime? PRO_ALT_UNT_BR_MOD_DATE { get; set; }
    public int? PRODUCT_ALT_UNT_COMP_ID { get; set; }
    public string PRO_ALT_UNT_COMP_DESC { get; set; }
    public byte[] PRO_ALT_UNT_COMP_LOGO { get; set; }
    public DateTime? PRO_ALT_UNT_COMP_REG_DATE { get; set; }
    public string PRO_ALT_UNT_COMP_ADDRESS { get; set; }
    public string PRO_ALT_UNT_COMP_PHONE { get; set; }
    public string PRO_ALT_UNT_COMP_PAN_NO { get; set; }
    public string PRO_ALT_UNT_COMP_EMAIL { get; set; }
    public string PRO_ALT_UNT_COMP_WEBSITE { get; set; }
    public bool? PRO_ALT_UNT_COMP_STATUS { get; set; }
    public DateTime? PRO_ALT_UNT_COMP_CREATE_DATE { get; set; }
    public string PRO_ALT_UNT_ENTER_BY { get; set; }
    public DateTime? PRO_ALT_UNT_ENTER_DATE { get; set; }
    public bool? PRO_ALT_UNT_STATUS { get; set; }
    public decimal? PRO_QNTY_CONV { get; set; }
    public decimal? PRO_ALT_QNTY_CONV { get; set; }
    public string PRO_VAL_TECH { get; set; }
    public bool? PRO_SERIAL_NO { get; set; }
    public bool? PRO_SIZE_WISE { get; set; }
    public bool? PRO_BATCH_WISE { get; set; }
    public decimal? PRO_BUY_RATE { get; set; }
    public decimal? PRO_SALES_RATE { get; set; }
    public decimal? PRO_MARGIN_ONE { get; set; }
    public decimal? PRO_TRADE_RATE { get; set; }
    public decimal? PRO_MARGIN_TWO { get; set; }
    public decimal? PRO_MARKED_PRICE { get; set; }
    public int? PRO_GRP_ID { get; set; }
    public string PRO_GRP_DESC { get; set; }
    public string PRO_GRP_SHORTNAME { get; set; }
    public decimal? PRO_GRP_MARGIN { get; set; }
    public string PRO_GRP_PRINTER { get; set; }
    public int? PRO_GRP_BRANCH_ID { get; set; }
    public string PRO_GRP_BR_DESC { get; set; }
    public string PRO_GRP_BR_SHORTNAME { get; set; }
    public DateTime? PRO_GRP_BR_REG_DATE { get; set; }
    public string PRO_GRP_BR_ADDRESS { get; set; }
    public string PRO_GRP_BR_PHONENO { get; set; }
    public string PRO_GRP_BR_EMAIL { get; set; }
    public string PRO_GRP_BR_CONTACT_PER { get; set; }
    public string PRO_GRP_BR_CONTACT_PER_ADD { get; set; }
    public string PRO_GRP_BR_CONTACT_PER_PH { get; set; }
    public string PRO_GRP_BR_CREATED_BY { get; set; }
    public DateTime? PRO_GRP_BR_CREATED_DATE { get; set; }
    public string PRO_GRP_BR_MODIFY_BY { get; set; }
    public DateTime? PRO_GRP_MODIFY_DATE { get; set; }
    public int? PRO_GRP_COMP_ID { get; set; }
    public string PRO_GRP_COMP_DESC { get; set; }
    public byte[] PRO_GRP_COMP_LOGO { get; set; }
    public DateTime? PRO_GRP_COMP_REG_DATE { get; set; }
    public string PRO_GRP_COMP_ADDRESS { get; set; }
    public string PRO_GRP_COMP_PHONE_NO { get; set; }
    public string PRO_GRP_COMP_PAN_NO { get; set; }
    public string PRO_GRP_COMP_EMAIL { get; set; }
    public string PRO_GRP_COMP_WEBSITE { get; set; }
    public bool? PRO_GRP_COMP_STATUS { get; set; }
    public DateTime? PRO_GRP_COMP_CREATED_DATE { get; set; }
    public DateTime? PRO_GRP_COMP_LOGIN_DATE { get; set; }
    public string PRO_GRP_COMP_PRINTDESC { get; set; }
    public bool? PRO_GRP_STATUS { get; set; }
    public string PRO_GRP_ENTER_BY { get; set; }
    public DateTime? PRO_GRP_ENTER_DATE { get; set; }
    public int? PRODUCT_SUB_GRP_ID { get; set; }
    public string PRODUCT_SUB_GRP_DESC { get; set; }
    public string PRODUCT_SUB_GRP_SHORTNAME { get; set; }
    public int? PRO_SUB_GRP_ID { get; set; }
    public string PRO_SUB_GRP_DESC { get; set; }
    public string PRO_SUB_GRP_SHORTNAME { get; set; }
    public decimal? PRO_SUB_GRP_MARGIN { get; set; }
    public string PRO_SUB_GRP_PRINTER { get; set; }
    public int? PRO_SUB_GRP_BRANCH_ID { get; set; }
    public string PSG_PRO_GRP_BR_DESC { get; set; }
    public string PSG_PRO_GRP_BR_SHORTNAME { get; set; }
    public DateTime? PSG_PRO_GRP_BR_REG_DATE { get; set; }
    public string PSG_PRO_GRP_BR_ADDRESS { get; set; }
    public string PSG_PRO_GRP_BR_PHONENO { get; set; }
    public string PSG_PRO_GRP_BR_FAX { get; set; }
    public string PSG_PRO_GRP_BR_EMAIL { get; set; }
    public string PSG_PRO_GRP_BR_CONTACT_PER { get; set; }
    public string PSG_PRO_GRP_BR_CONTACT_PER_ADD { get; set; }
    public string PSG_PRO_GRP_BR_CONTACT_PER_PH { get; set; }
    public string PSG_PRO_GRP_BR_CREATED_BY { get; set; }
    public DateTime? PSG_PR_GRP_BR_CREATED_DATE { get; set; }
    public string PSG_PRO_GRP_BR_MODIFY_BY { get; set; }
    public DateTime? PSG_PRO_GRP_BR_MODIFY_DATE { get; set; }
    public int? PSG_PRO_GRP_COMP_ID { get; set; }
    public string PSG_PRO_GRP_COMP_DESC { get; set; }
    public byte[] PSG_PRO_GRP_COMP_LOGO { get; set; }
    public DateTime? PSG_PRO_GRP_REG_DATE { get; set; }
    public string PSG_PRO_GRP_COMP_ADDRESS { get; set; }
    public string PSG_PRO_GRP_COMP_PHONE_NO { get; set; }
    public string PSG_PRO_GRP_COMP_PAN_NO { get; set; }
    public string PSG_PRO_GRP_COMP_EMAIL { get; set; }
    public string PSG_PRO_GRP_COMP_WEBSITE { get; set; }
    public string PSG_PRO_GRP_COMP_VERSION { get; set; }
    public bool? PSG_PRO_GRP_COMP_STATUS { get; set; }
    public DateTime? PSG_PRO_GRP_COMP_CREATED_DATE { get; set; }
    public DateTime? PSG_PRO_GRP_COMP_LOGIN_DATE { get; set; }
    public bool? PRO_SUB_GRP_STATUS { get; set; }
    public string PRO_SUB_GRP_ENTER_BY { get; set; }
    public DateTime? PRO_SUB_GRP_ENTER_DATE { get; set; }
    public int? PRODUCT_SUB_GRP_BRANCH_ID { get; set; }
    public string PRODUCT_SUB_GRP_BR_DESC { get; set; }
    public string PRODUCT_SUB_GRP_BR_SHORTNAME { get; set; }
    public DateTime? PRO_SUB_GRP_BR_REG_DATE { get; set; }
    public string PRO_SUB_GRP_BR_ADDRESS { get; set; }
    public string PRO_SUB_GRP_BR_PHONE { get; set; }
    public string PRO_SUB_GRP_BR_EMAIL { get; set; }
    public string PRO_SUB_GRP_BR_CONTCT_PER { get; set; }
    public string PRO_SUB_GRP_BR_CONTCT_PER_ADD { get; set; }
    public string PRO_SUB_GRP_BR_CONTCT_PER_PH { get; set; }
    public string PRO_SUB_GRP_BR_CREATED_BY { get; set; }
    public DateTime? PRO_SUB_GRP_BR_CREATED_DATE { get; set; }
    public string PRO_SUB_GRP_BR_MODIFY_BY { get; set; }
    public DateTime? PRO_SUB_GRP_BR_MODIFy_DATE { get; set; }
    public int? PRO_SUB_GRP_COMP_ID { get; set; }
    public string PRO_SUB_GRP_COMP_DESC { get; set; }
    public byte[] PRO_SUB_GRP_COMP_LOGO { get; set; }
    public DateTime? PRO_SUB_GRP_COMP_REG_DATE { get; set; }
    public string PRO_SUB_GRP_COMP_ADDRESS { get; set; }
    public string PRO_SUB_GRP_COMP_CITY { get; set; }
    public string PRO_SUB_GRP_COMP_PHONE { get; set; }
    public string PRO_SUB_GRP_COMP_PAN { get; set; }
    public string PRO_SUB_GRP_COMP_EMAIL { get; set; }
    public string PRO_SUB_GRP_COMP_WEBSITE { get; set; }
    public string PRO_SUB_GRP_COMP_PRINTDESC { get; set; }
    public string PRO_SUB_GRP_ENTERBY { get; set; }
    public DateTime? PRO_SUB_GRP_ENTERDATE { get; set; }
    public bool? PRODUCT_SUB_GRP_STATUS { get; set; }
    public decimal? PRODUCT_TAX { get; set; }
    public decimal? PRO_MIN_QTY { get; set; }
    public decimal? PRO_MAX_QTY { get; set; }
    public int? CMPID { get; set; }
    public int? CMPID1 { get; set; }
    public int? CMPID2 { get; set; }
    public int? CmpId3 { get; set; }
    public int? PRODUCT_BR_ID { get; set; }
    public string PRODUCT_BR_DESC { get; set; }
    public string PRODUCT_BR_SHORTNAME { get; set; }
    public DateTime? PRODUCT_BR_REG_DATE { get; set; }
    public string PRODUCT_BR_ADDRESS { get; set; }
    public string PRODUCT_BR_COUNTRY { get; set; }
    public string PRODUCT_BR_STATE { get; set; }
    public string PRODUCT_BR_CITY { get; set; }
    public string PRODUCT_BR_PHONE { get; set; }
    public string PRODUCT_BR_FAX { get; set; }
    public string PRODUCT_BR_EMAIL { get; set; }
    public string PRODUCT_BR_CONTACT_PER { get; set; }
    public string PRODUCT_BR_CONTACT_PER_ADD { get; set; }
    public string PRODUCT_BR_CONTACT_PER_PHONE { get; set; }
    public string PRODUCT_BR_CREATED_BY { get; set; }
    public DateTime? PRODUCT_BR_CREATED_DATE { get; set; }
    public string PRODUCT_BR_MODIFY_BY { get; set; }
    public DateTime? PRODUCT_BR_MODIFY_DATE { get; set; }
    public Guid PRODUCT_BR_SYNCGLOBALID { get; set; }
    public Guid PRODUCT_BR_SYNCORIGINID { get; set; }
    public DateTime? PRODUCT_BR_SyncCreatedOn { get; set; }
    public DateTime? PRODUCT_BR_SYNCLASTPATCHEDON { get; set; }
    public short? PRODUCT_BR_SYNCROWVERSION { get; set; }
    public Guid PRODUCT_BR_SYNCBASEDID { get; set; }
    public int? PRODUCT_COMP_ID { get; set; }
    public string PRODUCT_COMP_DESC { get; set; }
    public string PRODUCT_COMP_SHORTNAME { get; set; }
    public DateTime? PRODUCT_COMP_REGDATE { get; set; }
    public string PRODUCT_COMP_ADDRESS { get; set; }
    public string PRODUCT_COMP_COUNTRY { get; set; }
    public string PRODUCT_COMP_STATE { get; set; }
    public string PRODUCT_COMP_CITY { get; set; }
    public string PRODUCT_COMP_PHONE { get; set; }
    public string PRODUCT_COMP_FAX { get; set; }
    public string PRODUCT_COMP_EMAIL { get; set; }
    public string PRODUCT_COMP_CONTACT_PER { get; set; }
    public string PRODUCT_COMP_CONTACT_PER_ADD { get; set; }
    public string PRODUCT_COMP_CONTACT_PER_PHONE { get; set; }
    public int? PRODUCT_COMP_BRANCH_ID { get; set; }
    public string PRODUCT_COMP_UNIT_BR_DESC { get; set; }
    public string PRODUCT_COMP_UNIT_BR_SHORTNAME { get; set; }
    public DateTime? PRODUCT_COMP_UNIT_BR_REG_DATE { get; set; }
    public string PRODUCT_COMP_UNIT_BR_ADDRESS { get; set; }
    public string PRODUCT_COMP_UNIT_BR_COUNTRY { get; set; }
    public string PRODUCT_COMP_UNIT_BR_STATE { get; set; }
    public string PRODUCT_COMP_UNIT_BR_CITY { get; set; }
    public string PRODUCT_COMP_UNIT_BR_PHONENO { get; set; }
    public string PRODUCT_COMP_UNIT_BR_FAX { get; set; }
    public string PRODUCT_COMP_UNIT_BR_EMAIL { get; set; }
    public string PRODUCT_COMP_UNIT_BR_CONTACT_PER { get; set; }
    public string PRODUCT_COMP_UNIT_BR_CONTACT_PER_ADD { get; set; }
    public string PRODUCT_COMP_UNIT_BR_CONTACT_PER_PHONE { get; set; }
    public string PRODUCT_COMP_UNIT_BR_CREATED_BY { get; set; }
    public DateTime? PRODUCT_COMP_UNIT_BR_CREATED_DATE { get; set; }
    public string PRODUCT_COMP_UNIT_BR_MODIFIED_BY { get; set; }
    public DateTime? PRODUCT_COMP_UNIT_BR_MODIFIED_DATE { get; set; }
    public string PRODUCT_COMP_CREATED_BY { get; set; }
    public DateTime? PRODUCT_COMP_CREATED_DATE { get; set; }
    public long? PPL { get; set; }
    public long? PPR { get; set; }
    public long? PSL { get; set; }
    public long? PSR { get; set; }
    public long? PL_OPENING { get; set; }
    public long? PL_CLOSING { get; set; }
    public long? BS_CLOSING { get; set; }
    public byte[] PRODUCT_PIMAGE { get; set; }
    public string PRODUCT_ENTERBY { get; set; }
    public DateTime? PORDUCT_ENTERDATE { get; set; }
    public bool? PRODUCT_STATUS { get; set; }
    public decimal? PRODUCT_BEFOREBUYRATE { get; set; }
    public decimal? PRODUCT_BEFORESALESRATE { get; set; }
    public string PRODUCT_BARCODE { get; set; }
    public string PRODUCT_CHASISNO { get; set; }
    public string PRODUCT_ENGINENO { get; set; }
    public string PRODUCT_VEHICLE_COLOR { get; set; }
    public string PRODUCT_VEHICLE_MODEL { get; set; }
    public string PRODUCT_VEHICLE_NUMBER { get; set; }
    public string PRODUCT_BARCODE1 { get; set; }
    public string PRODUCT_BARCODE2 { get; set; }
    public string PRODUCT_BARCODE3 { get; set; }
    public int? GODOWN_ID { get; set; }
    public string GDN_DESC { get; set; }
    public string GDN_SHORTNAME { get; set; }
    public string GDN_LOCATION { get; set; }
    public decimal ALTERNATE_QUANTITY { get; set; }
    public int? PRO_ALT_UNIT_ID { get; set; }
    public string ALT_UNIT_DESC { get; set; }
    public string ALT_UNIT_SHORTNAME { get; set; }
    public decimal QUANTITY { get; set; }
    public int? PRO_UNIT_ID { get; set; }
    public string UNIT_DESC { get; set; }
    public string UNIT_SHORTNAME { get; set; }
    public decimal RATE { get; set; }
    public decimal BASIC_AMOUNT { get; set; }
    public decimal NET_AMOUNT { get; set; }
    public long? EXCHANGE_GLD { get; set; }
}