using System;

namespace PrintControl.PrintClass.SalesInvoice;

public class SbMaster
{
    public string VOUCHER_NO { get; set; }
    public DateTime VOUCHER_DATE { get; set; }
    public string VOUCHER_MITI { get; set; }
    public DateTime VOUCHER_TIME { get; set; }
    public string REF_VOUCHER_NO { get; set; }
    public DateTime? REF_VOUCHER_DATE { get; set; }
    public string REF_VOUCHER_MITI { get; set; }
    public long LEDGER_ID { get; set; }
    public string LEDGER_DESC { get; set; }
    public string LEDGER_SHORTNAME { get; set; }
    public string ACCOUNTING_CODE { get; set; }
    public string LEDGER_TYPE { get; set; }
    public int? ACCOUNT_GROUP_ID { get; set; }
    public string GROUP_DESC { get; set; }
    public string GROUP_SHORTNAME { get; set; }
    public int? GROUP_SCHEDULE { get; set; }
    public string LEDGER_NEPALI { get; set; }
    public int? ACCOUNT_SUB_GROUP_ID { get; set; }
    public string SUB_GROUP_DESC { get; set; }
    public string SUB_GROUP_SHORTNAME { get; set; }
    public string LEDGER_PAN { get; set; }
    public int? LEDGER_AREA_ID { get; set; }
    public int? LEDGER_AGENT_ID { get; set; }
    public int? lEDGER_CURRENCY_ID { get; set; }
    public decimal? LEDGER_CREDIT_DAYS { get; set; }
    public decimal? LEDGER_CREDIT_LIMIT { get; set; }
    public string LEDGER_CREDIT_TYPE { get; set; }
    public decimal? LEDGER_INTEREST_RATE { get; set; }
    public string LEDGER_ADDRESS { get; set; }
    public string LEDGER_PHONE_NO { get; set; }
    public string LEDGER_LAND_LINE_NO { get; set; }
    public string LEDGER_OWNER_DESC { get; set; }
    public string LEDGER_OWNER_NO { get; set; }
    public string LEDGER_EMAIL { get; set; }
    public string PARTY_DESC { get; set; }
    public string PARTY_VAT_NO { get; set; }
    public string PARTY_CONTACT_PERSON { get; set; }
    public string PARTY_MOBILE_NO { get; set; }
    public string PARTY_ADDRESS { get; set; }
    public string PARTY_CHEQUE_NO { get; set; }
    public DateTime? PARTY_CHEQUE_DATE { get; set; }
    public string VOUCHER_TYPE { get; set; }
    public string VOUCHER_MODE { get; set; }
    public string PAYMENT_MODE { get; set; }
    public int VOUCHER_DUE_DAYS { get; set; }
    public DateTime? VOUCHER_DUE_DATE { get; set; }
    public int? AGENT_ID { get; set; }
    public string AGENT_DESC { get; set; }
    public string AGENT_SHORTNAME { get; set; }
    public string AGENT_ADDRESS { get; set; }
    public string AGENT_PHONE_NO { get; set; }
    public int? SUBLEDGER_ID { get; set; }
    public string SUBLEDGER_DESC { get; set; }
    public string SUBLEDGER_SHORTNAME { get; set; }
    public string SUBLEDGER_ADDRESS { get; set; }
    public string SUBLEDGER_PHONE_NO { get; set; }
    public string ORDER_VOUCHER_NO { get; set; }
    public DateTime? ORDER_DATE { get; set; }
    public string CHALLAN_VOUCHER_NO { get; set; }
    public DateTime? CHALLAN_DATE { get; set; }
    public int? DEPATMENT_ID { get; set; }
    public string DEPARTMENT_DESC { get; set; }
    public string DEPATMENT_SHORTNAME { get; set; }
    public int? DEPARTMENT_ID_2 { get; set; }
    public int? DEPARTMENT_ID_3 { get; set; }
    public int? DEPARTMENT_ID_4 { get; set; }
    public int? COUNTER_ID { get; set; }
    public string COUNTER_DESC { get; set; }
    public string COUNTER_SHORTNAME { get; set; }
    public int CURRENCY_ID { get; set; }
    public string CURRENCY_DESC { get; set; }
    public string CURRENCY_SHORTNAME { get; set; }
    public decimal CURRENCY_RATE { get; set; }
    public decimal BASIC_AMOUNT { get; set; }
    public decimal TERM_AMOUNT { get; set; }
    public decimal NET_AMOUNT { get; set; }
    public decimal LOCAL_NET_AMOUNT { get; set; }
    public decimal VAT_AMOUNT { get; set; }
    public decimal TAXABLE_AMOUNT { get; set; }
    public decimal TENDER_AMOUNT { get; set; }
    public decimal RETURN_AMOUNT { get; set; }
    public string ACTION_TYPE { get; set; }
    public string NUM_IN_WORDS { get; set; }
    public string REMARKS { get; set; }
    public bool IS_CANCEL { get; set; }
    public bool IS_PRINTED { get; set; }
    public int NO_OF_PRINT { get; set; }
    public string PRINTED_BY { get; set; }
    public DateTime? PRINTED_DATE { get; set; }
    public bool? IS_LOCK { get; set; }
    public string ENTER_BY { get; set; }
    public DateTime ENTER_DATE { get; set; }
    public string RECONCILE_BY { get; set; }
    public DateTime? RECONCILE_DATE { get; set; }
    public string AUTHORIZED_BY { get; set; }
    public DateTime? AUTHORIZED_DATE { get; set; }
    public string CLEARING_BY { get; set; }
    public DateTime? CLEARING_DATE { get; set; }
    public string CANCEL_BY { get; set; }
    public DateTime? CANCEL_DATE { get; set; }
    public string CANCEL_REMARKS { get; set; }
    public int? COMPANY_UNIT_ID { get; set; }
    public string COMPANY_UNIT_DESC { get; set; }
    public string COMPANY_UNIT_SHORTNAME { get; set; }
    public int BRANCH_UNIT_ID { get; set; }
    public string BRANCH_DESC { get; set; }
    public string BRANCH_SHORTNAME { get; set; }
    public bool? IS_API_POSTED { get; set; }
    public bool? IS_REAL_TIME { get; set; }
    public int FISCAL_YEAR_ID { get; set; }
    public int? MEMBER_SHIP_ID { get; set; }
    public string MEMBER_DESC { get; set; }
    public string MEMBER_SHORTNAME { get; set; }
    public string MEMBER_PHONE_NO { get; set; }
    public string MEMBER_EMAIL_ADDRESS { get; set; }
    public string MEMBER_PRICE_TAG { get; set; }
    public string MEMBER_TYPE_DESC { get; set; }
    public string MEMBER_TYPE_SHORTNAME { get; set; }
    public decimal? MEMBER_DISCOUNT { get; set; }
    public int? TABLE_ID { get; set; }
    public string TABLE_DESC { get; set; }
    public string TABLE_SHORTNAME { get; set; }
    public int? DOCTOR_ID { get; set; }
    public string DOCTOR_DESC { get; set; }
    public string DOCTOR_SHORTNAME { get; set; }
    public long? PATIENT_ID { get; set; }
    public string PATIENT_DESC { get; set; }
    public string PATIENT_SHORTNAME { get; set; }
    public string PATIENT_LEDGER { get; set; }
    public string PATIENT_TEMP_ADDRESS { get; set; }
    public string PATIENT_PER_ADDRESS { get; set; }
    public decimal? PATIENT_AGE { get; set; }
    public string PATIENT_CONTACT_NO { get; set; }
    public int? HOSPITAL_DEPARTMENT_ID { get; set; }
    public string HOSPITAL_DEPARTMENT { get; set; }
    public string HOSPITAL_DEPARTMENT_SHORTNAME { get; set; }
    public long? GLID { get; set; }
    public int? GrpId { get; set; }
    public int? SubGrpId { get; set; }
    public int? AgentId { get; set; }
    public int? SLId { get; set; }
    public int? CmpUnit_ID { get; set; }
    public int? FY_Id { get; set; }
    public int? MShipId { get; set; }
    public int? MemberTypeId { get; set; }
    public int? TableId { get; set; }
    public int? DrId { get; set; }
    public long? PaitentId { get; set; }
    public int? DId { get; set; }
}