IF COL_LENGTH('AMS.CompanyInfo', 'PrintDesc') IS NULL BEGIN
	ALTER TABLE AMS.CompanyInfo
	ADD PrintDesc NVARCHAR(200) NULL;
END;

IF COL_LENGTH('AMS.CompanyInfo', 'IsSyncOnline') IS NULL BEGIN
	ALTER TABLE AMS.CompanyInfo
	ADD IsSyncOnline BIT NULL;
END;

IF COL_LENGTH('AMS.Branch', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.Branch
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Branch', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.Branch
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Branch', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.Branch
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Branch', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.Branch
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Branch', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.Branch
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.Branch', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.Branch
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CompanyUnit', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.CompanyUnit
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CompanyUnit', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.CompanyUnit
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CompanyUnit', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.CompanyUnit
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CompanyUnit', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.CompanyUnit
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CompanyUnit', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.CompanyUnit
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.CompanyUnit', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.CompanyUnit
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Currency', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.Currency
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Currency', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.Currency
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Currency', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.Currency
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Currency', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.Currency
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Currency', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.Currency
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.Currency', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.Currency
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountGroup', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.AccountGroup
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountGroup', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.AccountGroup
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountGroup', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.AccountGroup
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.AccountGroup', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.AccountGroup
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.AccountGroup', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.AccountGroup
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.AccountGroup', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.AccountGroup
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountSubGroup', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.AccountSubGroup
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountSubGroup', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.AccountSubGroup
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountSubGroup', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.AccountSubGroup
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.AccountSubGroup', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.AccountSubGroup
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.AccountSubGroup', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.AccountSubGroup
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.AccountSubGroup', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.AccountSubGroup
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'PhoneNo') IS NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ALTER COLUMN PhoneNo NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'PhoneNo') IS NOT NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ALTER COLUMN PhoneNo NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.SeniorAgent', 'Address') IS NOT NULL BEGIN
	ALTER TABLE AMS.SeniorAgent
	ALTER COLUMN Address NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'PhoneNo') IS NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ALTER COLUMN PhoneNo NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'PhoneNo') IS NOT NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ALTER COLUMN PhoneNo NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.JuniorAgent', 'Address') IS NOT NULL BEGIN
	ALTER TABLE AMS.JuniorAgent
	ALTER COLUMN Address NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.MainArea', 'MCountry') IS NOT NULL BEGIN
	ALTER TABLE AMS.MainArea
	ALTER COLUMN MCountry NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.Area', 'Country') IS NOT NULL BEGIN
	ALTER TABLE AMS.Area
	ALTER COLUMN Country NVARCHAR(50) NULL;
END;

IF COL_LENGTH('AMS.GeneralLedger', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.GeneralLedger
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.GeneralLedger', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.GeneralLedger
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.GeneralLedger', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.GeneralLedger
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.GeneralLedger', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.GeneralLedger
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.GeneralLedger', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.GeneralLedger
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.GeneralLedger', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.GeneralLedger
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.GeneralLedger', 'SyncBaseId') IS NOT NULL BEGIN
	ALTER TABLE AMS.GeneralLedger
	ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AUD.AUDIT_SUBLEDGER', 'GLID') IS NULL BEGIN
	ALTER TABLE [AUD].[AUDIT_SUBLEDGER]
	ALTER COLUMN [GLID] NVARCHAR(100) NULL;
END;

IF COL_LENGTH('AMS.Subledger', 'GLID') IS NULL BEGIN
	ALTER TABLE [AMS].[Subledger]
	ALTER COLUMN [GLID] NVARCHAR(100) NULL;
END;

IF COL_LENGTH('AMS.Subledger', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.Subledger
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Subledger', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.Subledger
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Subledger', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.Subledger
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Subledger', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.Subledger
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Subledger', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.Subledger
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.Subledger', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.Subledger
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'MemberId') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup
	ALTER COLUMN MemberId BIGINT NOT NULL;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.MemberType', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.MemberType
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.MemberType', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.MemberType
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.MemberType', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.MemberType
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.MemberType', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.MemberType
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.MemberType', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.MemberType
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.MemberType', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.MemberType
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.TableMaster', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.TableMaster
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.TableMaster', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.TableMaster
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.TableMaster', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.TableMaster
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.TableMaster', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.TableMaster
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.TableMaster', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.TableMaster
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.TableMaster', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.TableMaster
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.TableMaster', 'IsPrePaid') IS NULL BEGIN
	ALTER TABLE AMS.TableMaster
	ADD IsPrePaid BIT;
END;

IF COL_LENGTH('AMS.CostCenter', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.CostCenter
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CostCenter', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.CostCenter
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CostCenter', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.CostCenter
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CostCenter', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.CostCenter
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CostCenter', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.CostCenter
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.CostCenter', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.CostCenter
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Product', 'EngineNo') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD EngineNo NVARCHAR(100) NULL;
END;

IF COL_LENGTH('AMS.Product', 'VHNumber') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD VHNumber NVARCHAR(100) NULL;
END;

IF COL_LENGTH('AMS.Product', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Product', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Product', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Product', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Product', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.Product', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.Product
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductGroup', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductGroup
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductGroup', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.ProductGroup
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductGroup', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.ProductGroup
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductGroup', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductGroup
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductGroup', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductGroup
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductGroup', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.ProductGroup
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.ProductGroup', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductGroup
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductSubGroup', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductSubGroup
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductSubGroup', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.ProductSubGroup
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductSubGroup', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.ProductSubGroup
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductSubGroup', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductSubGroup
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductSubGroup', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductSubGroup
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductSubGroup', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.ProductSubGroup
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.ProductSubGroup', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductSubGroup
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductUnit', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductUnit
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductUnit', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.ProductUnit
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductUnit', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.ProductUnit
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductUnit', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductUnit
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductUnit', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductUnit
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductUnit', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.ProductUnit
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.ProductUnit', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductUnit
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.DocumentNumbering', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.DocumentNumbering
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.DocumentNumbering', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.DocumentNumbering
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.DocumentNumbering', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.DocumentNumbering
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.DocumentNumbering', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.DocumentNumbering
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.DocumentNumbering', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.DocumentNumbering
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.DocumentNumbering', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.DocumentNumbering
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.DocumentNumbering', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.DocumentNumbering
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.LedgerOpening', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.LedgerOpening
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.LedgerOpening', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.LedgerOpening
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.LedgerOpening', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.LedgerOpening
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.LedgerOpening', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.LedgerOpening
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.LedgerOpening', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.LedgerOpening
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.LedgerOpening', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.LedgerOpening
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.LedgerOpening', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.LedgerOpening
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'CompanyUnitId') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD CompanyUnitId INT NULL;
END;

IF COL_LENGTH('AMS.NR_Master', 'BranchId') IS NULL BEGIN
	ALTER TABLE AMS.NR_Master
	ADD BranchId INT NULL;
END;

IF COL_LENGTH('AMS.PO_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PO_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PO_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PO_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PO_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PO_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PO_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PO_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PO_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PO_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PO_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PO_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PO_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PO_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PO_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PO_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PO_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PO_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PO_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PO_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PO_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PC_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PC_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PC_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PC_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PC_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PC_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PC_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PC_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PC_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PC_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PC_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PC_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PC_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PC_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PC_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PC_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PC_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PC_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PC_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PC_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PB_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PB_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PB_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PB_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PB_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PB_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PB_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PB_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PB_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PB_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PB_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PB_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PB_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PB_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PB_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PB_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PB_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PB_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PB_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PB_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PR_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PR_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PR_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PR_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PR_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PR_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PR_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PR_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PR_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PR_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PR_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PR_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PR_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PR_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'PAttachment1') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD [PAttachment1] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'PAttachment2') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD [PAttachment2] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'PAttachment3') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD [PAttachment3] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'PAttachment4') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD [PAttachment4] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'PAttachment5') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD [PAttachment5] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'FiscalYearId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD FiscalYearId INT;
END;

IF COL_LENGTH('AMS.PAB_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PAB_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PAB_Details', 'FiscalYearId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Details
	ADD FiscalYearId INT;
END;

IF COL_LENGTH('AMS.PAB_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PAB_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PAB_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PAB_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PAB_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PAB_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PAB_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Master', 'FiscalYearId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Master
	ADD FiscalYearId INT;
END;

IF COL_LENGTH('AMS.PBT_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PBT_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PBT_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PBT_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Details', 'FiscalYearId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Details
	ADD FiscalYearId INT;
END;

IF COL_LENGTH('AMS.PBT_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PBT_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PBT_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PBT_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Term', 'FiscalYearId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Term
	ADD FiscalYearId INT;
END;

IF COL_LENGTH('AMS.PBT_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PBT_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PBT_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PBT_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PBT_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PBT_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SQ_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SQ_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SQ_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SQ_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SQ_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SQ_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SQ_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SQ_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SQ_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SQ_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SQ_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SO_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SO_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SO_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SO_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SO_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SO_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SO_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SO_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SO_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SO_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SO_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SO_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SO_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SO_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SO_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SO_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SO_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SO_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SO_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SO_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SC_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SC_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SC_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SC_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SC_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SC_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SC_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SC_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SC_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SC_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SC_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SC_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SC_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SC_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SC_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SC_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SC_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SC_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SC_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SC_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SB_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SB_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SB_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SB_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SB_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SB_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SB_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SB_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SB_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SB_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SB_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SB_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SB_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SB_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SB_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SB_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SB_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SB_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SB_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SB_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SR_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SR_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SR_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SR_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SR_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SR_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SR_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SR_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SR_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Term', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Term
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Term', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Term
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.SR_Term', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.SR_Term
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SR_Term', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.SR_Term
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.SR_Term', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.SR_Term
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.SR_Term', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.SR_Term
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CB_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CB_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CB_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.CB_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CB_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.CB_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CB_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.CB_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.CB_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CB_Master', 'In_Words') IS NULL BEGIN
	ALTER TABLE AMS.CB_Master
	ADD In_Words NVARCHAR(1024) NULL;
END;
IF COL_LENGTH('AMS.CB_Details', 'CBLedgerId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD CBLedgerId BIGINT NULL;
END;
IF COL_LENGTH('AMS.CB_Details', 'CurrencyId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD CurrencyId INT NULL;
END;

IF COL_LENGTH('AMS.CB_Details', 'CurrencyRate') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD CurrencyRate DECIMAL(18, 6) NULL;
END;

IF COL_LENGTH('AMS.CB_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CB_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.CB_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CB_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.CB_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.CB_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.CB_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JV_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.JV_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JV_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.JV_Master
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JV_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.JV_Master
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.JV_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.JV_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.JV_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.JV_Master
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.JV_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.JV_Master
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JV_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.JV_Details
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JV_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.JV_Details
	ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.JV_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.JV_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.JV_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.JV_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.JV_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.JV_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.JV_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.JV_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Notes_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Details ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Notes_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Details ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.Notes_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Details
	ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Notes_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Details
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.Notes_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Details
	ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.Notes_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Details
	ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PostDateCheque', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.PostDateCheque
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PostDateCheque', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.PostDateCheque ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.PostDateCheque', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.PostDateCheque ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PostDateCheque', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.PostDateCheque ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.PostDateCheque', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.PostDateCheque ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.PostDateCheque', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.PostDateCheque ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.BOM_Master ', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE INV.BOM_Master
	ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.BOM_Master ', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE INV.BOM_Master ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.BOM_Master ', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE INV.BOM_Master ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.BOM_Master ', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE INV.BOM_Master ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.BOM_Master ', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE INV.BOM_Master ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('INV.BOM_Master ', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE INV.BOM_Master ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.BOM_Details ', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE INV.BOM_Details ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.BOM_Details ', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE INV.BOM_Details ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.BOM_Details ', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE INV.BOM_Details ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.BOM_Details ', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE INV.BOM_Details ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.BOM_Details ', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE INV.BOM_Details ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('INV.BOM_Details ', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE INV.BOM_Details ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.FGR_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Master ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.FGR_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Master ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.FGR_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Master ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.FGR_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Master ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.FGR_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Master ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.FGR_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Master ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.FGR_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Details ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.FGR_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Details ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.FGR_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Details ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.FGR_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Details ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.FGR_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Details ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.FGR_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.FGR_Details ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.Production_Master', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE INV.Production_Master ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.Production_Master', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE INV.Production_Master ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.Production_Master', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE INV.Production_Master ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.Production_Master', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE INV.Production_Master
	ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.Production_Master', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE INV.Production_Master ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('INV.Production_Master', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE INV.Production_Master ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.Production_Details', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE INV.Production_Details ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.Production_Details', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE INV.Production_Details ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('INV.Production_Details', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE INV.Production_Details ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.Production_Details', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE INV.Production_Details ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('INV.Production_Details', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE INV.Production_Details ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('INV.Production_Details', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE INV.Production_Details ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.StockDetails', 'PurRefvno') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD PurRefvno NVARCHAR(50);
END;

IF COL_LENGTH('AMS.StockDetails', 'AddStockVal') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD AddStockVal DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.StockDetails', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.StockDetails', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.StockDetails', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.StockDetails', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.StockDetails', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.StockDetails', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.StockDetails ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountDetails', 'PartyName') IS NULL BEGIN
	ALTER TABLE AMS.AccountDetails
	ALTER COLUMN PartyName NVARCHAR(100);
END;

IF COL_LENGTH('AMS.AccountDetails', 'SyncGlobalId') IS NULL BEGIN
	ALTER TABLE AMS.AccountDetails ADD SyncGlobalId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountDetails', 'SyncOriginId') IS NULL BEGIN
	ALTER TABLE AMS.AccountDetails ADD SyncOriginId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.AccountDetails', 'SyncCreatedOn') IS NULL BEGIN
	ALTER TABLE AMS.AccountDetails ADD SyncCreatedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.AccountDetails', 'SyncLastPatchedOn') IS NULL BEGIN
	ALTER TABLE AMS.AccountDetails ADD SyncLastPatchedOn DATETIME NULL;
END;

IF COL_LENGTH('AMS.AccountDetails', 'SyncRowVersion') IS NULL BEGIN
	ALTER TABLE AMS.AccountDetails ADD SyncRowVersion SMALLINT NULL;
END;

IF COL_LENGTH('AMS.AccountDetails', 'SyncBaseId') IS NULL BEGIN
	ALTER TABLE AMS.AccountDetails ADD SyncBaseId UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('AMS.BarcodeList', 'MRP') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList ADD MRP DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.BarcodeList', 'Trade') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList ADD Trade DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.BarcodeList', 'Wholesale') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList ADD Wholesale DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.BarcodeList', 'Retail') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList ADD Retail DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.BarcodeList', 'Dealer') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList ADD Dealer DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.BarcodeList', 'Resellar') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList ADD Resellar DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.BarcodeList', 'UnitId') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList
	ADD UnitId INT;
END;

IF COL_LENGTH('AMS.BarcodeList', 'AltUnitId') IS NULL BEGIN
	ALTER TABLE AMS.BarcodeList ADD AltUnitId INT;
END;

IF COL_LENGTH('AMS.MemberShipSetup', 'PriceTag') IS NULL BEGIN
	ALTER TABLE AMS.MemberShipSetup ADD PriceTag NVARCHAR(50);
END;

IF COL_LENGTH('AMS.SystemConfiguration', 'ResturantDesignInvoice') IS NULL BEGIN
	ALTER TABLE AMS.SystemConfiguration ADD ResturantDesignInvoice VARCHAR(250);
END;

IF COL_LENGTH('AMS.PR_Master', 'R_Invoice') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master ADD R_Invoice BIT NULL;
END;

IF COL_LENGTH('AMS.SR_Details', 'PDiscountRate') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details ADD PDiscountRate DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.SR_Details', 'PDiscount') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details ADD PDiscount DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.SR_Details', 'BDiscountRate') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details ADD BDiscountRate DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.SR_Details', 'BDiscount') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details
	ADD BDiscount DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.SR_Details', 'ServiceChargeRate') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details ADD ServiceChargeRate DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.SR_Details', 'ServiceCharge') IS NULL BEGIN
	ALTER TABLE AMS.SR_Details ADD ServiceCharge DECIMAL(18, 6);
END;

IF COL_LENGTH('AMS.Scheme_Master', 'EnterBy') IS NULL BEGIN
	ALTER TABLE AMS.Scheme_Master ADD EnterBy NVARCHAR(50);
END;

IF COL_LENGTH('AMS.Scheme_Master', 'EnterDate') IS NULL BEGIN
	ALTER TABLE AMS.Scheme_Master ADD EnterDate DATETIME;
END;

IF COL_LENGTH('AMS.ProductOpening', 'IsReverse') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening ADD IsReverse BIT NULL;
END;

IF COL_LENGTH('AMS.ProductOpening', 'Remarks') IS NULL BEGIN
	ALTER TABLE AMS.ProductOpening ADD Remarks NVARCHAR(512) NULL;
END;

IF COL_LENGTH('AMS.SalesSetting', 'SBRemarksEnable') IS NULL BEGIN
	ALTER TABLE AMS.SalesSetting ADD SBRemarksEnable BIT NULL;
END;

IF COL_LENGTH('AMS.SalesSetting', 'SBRemarksMandatory') IS NULL BEGIN
	ALTER TABLE AMS.SalesSetting ADD SBRemarksMandatory BIT NULL;
END;

IF COL_LENGTH('AMS.PurchaseSetting', 'PBRemarksEnable') IS NULL BEGIN
	ALTER TABLE AMS.PurchaseSetting ADD PBRemarksEnable BIT NULL;
END;

IF COL_LENGTH('AMS.PurchaseSetting', 'PBRemarksMandatory') IS NULL BEGIN
	ALTER TABLE AMS.PurchaseSetting ADD PBRemarksMandatory BIT NULL;
END;

IF COL_LENGTH('AMS.PurchaseSetting', 'PBIndentMandatory') IS NULL BEGIN
	ALTER TABLE AMS.PurchaseSetting ADD PBIndentMandatory BIT NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'PAttachment1') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master ADD [PAttachment1] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'PAttachment2') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master ADD [PAttachment2] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'PAttachment3') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master ADD [PAttachment3] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'PAttachment4') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master ADD [PAttachment4] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.PR_Master', 'PAttachment5') IS NULL BEGIN
	ALTER TABLE AMS.PR_Master ADD [PAttachment5] [IMAGE] NULL;
END;
IF COL_LENGTH('AMS.Notes_Master', 'PAttachment1') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD [PAttachment1] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'PAttachment2') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD [PAttachment2] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'PAttachment3') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD [PAttachment3] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'PAttachment4') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD [PAttachment4] [IMAGE] NULL;
END;

IF COL_LENGTH('AMS.Notes_Master', 'PAttachment5') IS NULL BEGIN
	ALTER TABLE AMS.Notes_Master ADD [PAttachment5] [IMAGE] NULL;
END;