IF OBJECT_ID ( 'VM.VIEW_COMPANY_PROFILES' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_COMPANY_PROFILES as Select Database_Name DATABASE_ID,Company_Name as COMPANY_DESC,Company_Logo lOGO,CReg_Date REGISTRATION_DATE,Address COMPANY_ADDRESS,Country COMPANY_COUNTRY,State COMPANY_STATE,City COMPANY_CITY,PhoneNo COMPANY_OFFICE_NUMBER, Fax COMPANY_FAX_NO,Pan_No COMPANY_TPAN_OR_VAT, Email COMPANY_EMAIL, Website COMPANY_WEBSITE from AMS.CompanyInfo ');
  END;
IF OBJECT_ID ( 'VM.VIEW_JOURNAL_VOUCHER' ) IS NULL
  BEGIN
    EXECUTE ('Create View VM.VIEW_JOURNAL_VOUCHER as SELECT 0 AS ROW_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_LEDGEROPENING' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_LEDGEROPENING AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_MATERIALIZED_VIEW' ) IS NULL
  BEGIN
    EXECUTE ('CREATE View VM.VIEW_MATERIALIZED_VIEW as Select '''' FISCAL_YEAR');
  END;
IF OBJECT_ID ( 'VM.VIEW_PR_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PR_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PR_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PR_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PB_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PB_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PB_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PB_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PB_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PB_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PB_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PB_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PB_OTHER_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PB_OTHER_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PO_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PO_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PO_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PO_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PC_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PC_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PC_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PC_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PIN_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PIN_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PIN_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PIN_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SR_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SR_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SR_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SR_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SR_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SR_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SR_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SR_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SR_MASTER_OTHER_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SR_MASTER_OTHER_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SO_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SO_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SO_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SO_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SO_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SO_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SO_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SO_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SO_MASTER_OTHER_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SO_MASTER_OTHER_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SB_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SB_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SB_EXCHANGE_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SB_EXCHANGE_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SB_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SB_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SC_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SC_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SC_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SC_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SC_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SC_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SC_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SC_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SC_MASTER_OTHER_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SC_MASTER_OTHER_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SQ_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SQ_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SQ_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SQ_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_JV_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_JV_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_JV_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_JV_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_CB_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_CB_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_CB_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_CB_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_NOTES_MASTER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_NOTES_MASTER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_NOTES_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_NOTES_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_POST_DATE_CHEQUE' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_POST_DATE_CHEQUE AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_GENERAL_LEDGER' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_GENERAL_LEDGER AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_ST_TERM_PRODUCT ' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_ST_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_ST_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_ST_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SB_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SB_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SB_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SB_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SB_MASTER_OTHER_DETAILS' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SB_MASTER_OTHER_DETAILS AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SQ_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SQ_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_SQ_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_SQ_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PR_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PR_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PR_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PR_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PO_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PO_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PO_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PO_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PC_TERM_PRODUCT' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PC_TERM_PRODUCT AS SELECT '''' VOUCHER_NO');
  END;
IF OBJECT_ID ( 'VM.VIEW_PC_TERM_BILL' ) IS NULL
  BEGIN
    EXECUTE ('CREATE VIEW VM.VIEW_PC_TERM_BILL AS SELECT '''' VOUCHER_NO');
  END;