
USE MR_BBSCS04
DROP TRIGGER AMS.TR_PREVENT_UPDATE_FROM_SR_Term
SELECT * FROM AMS.ST_Term WHERE ST_ID ='2'
UPDATE MR_BBSCO03.AMS.SR_Term SET Term_Type = 'B' WHERE ST_Id = '2' AND Term_Type ='P'

USE MR_BBSCS04
DROP TRIGGER AMS.TR_PREVENT_UPDATE_FROM_SR_Term
SELECT * FROM MR_BBSCO04.AMS.ST_Term WHERE ST_ID ='2'
UPDATE MR_BBSCS04.AMS.SR_Term SET Term_Type = 'B' WHERE ST_Id = '2' AND Term_Type ='P'

USE MR_BBSCK02
DROP TRIGGER AMS.TR_PREVENT_UPDATE_FROM_SR_Term
SELECT * FROM MR_BBSCK02.AMS.ST_Term WHERE ST_ID ='2'
UPDATE MR_BBSCK02.AMS.SR_Term SET Term_Type = 'B' WHERE ST_Id = '2' AND Term_Type ='P'

USE MR_BBSCS03
DROP TRIGGER AMS.TR_PREVENT_UPDATE_FROM_SR_Term
SELECT * FROM MR_BBSCS03.AMS.ST_Term WHERE ST_ID ='2'
UPDATE MR_BBSCS03.AMS.SR_Term SET Term_Type = 'B' WHERE ST_Id = '2' AND Term_Type ='P'

USE MR_SSCCOU01
DROP TRIGGER AMS.TR_PREVENT_UPDATE_FROM_SR_Term
SELECT * FROM MR_SSCCOU01.AMS.ST_Term WHERE ST_ID ='2'
UPDATE MR_SSCCOU01.AMS.SR_Term SET Term_Type = 'B' WHERE ST_Id = '2' AND Term_Type ='P'

USE MR_BBSCO04
DROP TRIGGER AMS.TR_PREVENT_UPDATE_FROM_SR_Term
SELECT * FROM MR_BBSCO04.AMS.ST_Term WHERE ST_ID ='2'
UPDATE MR_BBSCO04.AMS.SR_Term SET Term_Type = 'B' WHERE ST_Id = '2' AND Term_Type ='P'


