IF NOT EXISTS (SELECT *
			FROM AMS.DocumentNumbering
			WHERE FiscalYearId='13')BEGIN
DECLARE @FiscalYear VARCHAR(50) ='/79-80';
DECLARE @FiscalYearId INT=13;
DECLARE @DocStartDate VARCHAR(10) ='2022-07-16';
DECLARE @DocStartMiti VARCHAR(10) ='01/04/2079';
DECLARE @DocEndDate VARCHAR(10) ='2023-07-15';
DECLARE @DocEndMiti VARCHAR(10) ='31/03/2080';
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SB', N'admin', N'INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, N'A', N'ASB/', @FiscalYear, 5, 15, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'TSB', N'admin', N'HOLD INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, N'A', N'ASB/', @FiscalYear, 5, 15, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'RSO', N'admin', N'ORDER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'RSO/', @FiscalYear, 5, 15, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SR', N'admin', N'RETURN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SR/', @FiscalYear, 5, 14, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SO', N'admin', N'ORDER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SO/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PB', N'admin', N'INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PB/', @FiscalYear, 5, 14, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PR', N'admin', N'RETURN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PR/', @FiscalYear, 5, 14, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'CV', N'admin', N'VOUCHER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'CV/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'JV', N'admin', N'VOUCHER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'JV/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'DN', N'admin', N'DEBIT NOTES 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'DN/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'CN', N'admin', N'NOTES 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'CN/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'COA', N'admin', N'LEDGER OPENING 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'COA/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'POP', N'admin', N'PRODUCT OPENING 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'POP/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PDC', N'admin', N'PDC 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PDC/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PI', N'admin', N'INDENT 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PI/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PQ', N'admin', N'QUOTATION 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PQ/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PO', N'admin', N'ORDER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PO/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'GIT', N'admin', N'TRANSIT 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'GIT/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PC', N'admin', N'CHALLAN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PC/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PIB', N'admin', N'INTERBRANCH INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PIB/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PQC', N'admin', N'QUALITY CONTROL 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PQC/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PAB', N'admin', N'ADDITIONAL INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PAB/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PBT', N'admin', N'TRAVEL & TOUR INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PBT/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PEB', N'admin', N'EXPIRY & BREAKAGE RETURN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PEB/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SQ', N'admin', N'QUOTATION 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SQ/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SOC', N'admin', N'ORDER CANCELLATION 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SOC/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SDO', N'admin', N'DISPATCH ORDER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SDO/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SDOC', N'admin', N'DISPATCH ORDER CANCELLATION 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SDOC/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SC', N'admin', N'CHALLAN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SC/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SIB', N'admin', N'INTER BRANCH 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SIB/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SAB', N'admin', N'ADDITIONAL INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SAB/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'POS', N'admin', N'POS BILLING 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'POS/', @FiscalYear, 5, 15, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'RSB', N'admin', N'RESTRO INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'RSB/', @FiscalYear, 5, 15, 1, N'0', 1, NULL, 1, 1, 99999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'ATI', N'admin', N'ABBREVIATE TAX INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'ATI/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SEB', N'admin', N'EXPIRY & BREAKAGE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SEB/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SBT', N'admin', N'TRAVEL & TOUR INVOICE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SBT/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'GT', N'admin', N'GODOWN TRANSFER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'GT/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SA', N'admin', N'STOCK ADJUSTMENT 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SA/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'PSA', N'admin', N'PHYSICAL STOCK 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'PSA/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'STEB', N'admin', N'TRANSFER EXPIRY & BREAKAGE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'STEB/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'ASSM', N'admin', N'ASSEMBLY MASTER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'ASSM/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'BOM', N'admin', N'MEMO 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'BOM/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'SREQ', N'admin', N'INVENTORY REQUOSITION 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'SREQ/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'MI', N'admin', N'INVENTORY ISSUE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'MI/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'MIR', N'admin', N'INVENTORY ISSUE RETURN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'MIR/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'MR', N'admin', N'INVENTORY RECEIVE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'MR/', @FiscalYear, 4, 13, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'MRR', N'admin', N'INVENTORY RECEIVE RETURN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'MRR/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'MBOM', N'admin', N'MEMO MASTER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'MBOM/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'IBOM', N'admin', N'PRODUCTION MEMO 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'IBOM/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'IREQ', N'admin', N'PRODUCTION REQUISITION 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'IREQ/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'RMI', N'admin', N'PRODUCTION ISSUE 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'RMI/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'RMIR', N'admin', N'PRODUCTION ISSUE RETURN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'RMIR/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'FGR', N'admin', N'FINISHED GOODS RECEIVED 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'FGR/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'FGRR', N'admin', N'FINISHED GOODS RETURN 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'FGRR/', @FiscalYear, 4, 15, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
INSERT INTO AMS.DocumentNumbering(DocId, DocModule, DocUser, DocDesc, DocStartDate, DocStartMiti, DocEndDate, DocEndMiti, DocType, DocPrefix, DocSufix, DocBodyLength, DocTotalLength, DocBlank, DocBlankCh, DocBranch, DocUnit, DocStart, DocCurr, DocEnd, DocDesign, Status, EnterBy, EnterDate, FiscalYearId, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT (SELECT ISNULL(MAX(dn.DocId), 0)+1
		FROM AMS.DocumentNumbering dn), N'IPO', N'admin', N'PRODUCTION ORDER 2079', @DocStartDate, @DocStartMiti, @DocStartDate, @DocStartMiti, 'A', N'IPO/', @FiscalYear, 4, 14, 1, N'0', 1, NULL, 1, 1, 9999, NULL, 1, N'admin', GETDATE(), @FiscalYearId, NULL, NULL, NULL, NULL, NULL, 1;
END;