
INSERT INTO dbo.CUSTOMER_SETUP(CUSTOMER_CODE, CUSTOMER_DESC, NEPALI_NAME, ADDRESS, PAN_NO, PHONE_NO, MOBILE_NO, REMARKS, GROUP_FLAG, MASTER_CODE, PRE_CODE, ACCOUNT_CODE, MEMBERSHIP_CODE, EMAIL_ID, BANK_NAME, BANK_AC_NO, LC_NO, PRICE_LEVEL, BILL_WISE, IS_CASH_CUSTOMER, CUSTOMER_TYPE, CREATED_DATE, CREATED_BY, MODIFY_BY, MODIFY_DATE, ENABLE_COSTENTER, CREDIT_DAYS, CREDIT_LIMIT, CUSTOMER_ID, ENABLE_TDS, FIXED_DISCOUNT, PACKAGE_CODE, PACKAGE_AMOUNT, MOBILE_NO2, MOBILE_NO3, EXCISE_REG_NO, LOCK_FLAG, AGE, CARE_OF, FPAN_NO, ENABLE_CREDIT_LIMIT, BILL_TO, SHIP_TO, MODE_OF_PAYMENT)
SELECT GrpId CUSTOMER_CODE,GrpName CUSTOMER_DESC,NepaliDesc NEPALI_NAME,NULL ADDRESS,NULL PAN_NO,NULL PHONE_NO,NULL MOBILE_NO, NULL REMARKS,'G' GROUP_FLAG,NULL MASTER_CODE,NULL PRE_CODE,NULL ACCOUNT_CODE,NULL MEMBERSHIP_CODE,NULL EMAIL_ID,
NULL BANK_NAME,NULL BANK_AC_NO,NULL LC_NO,NULL PRICE_LEVEL,NULL BILL_WISE,NULL IS_CASH_CUSTOMER,NULL CUSTOMER_TYPE,NULL CREATED_DATE,NULL CREATED_BY,NULL MODIFY_BY,NULL MODIFY_DATE,NULL ENABLE_COSTENTER,NULL CREDIT_DAYS,NULL CREDIT_LIMIT,NULL CUSTOMER_ID,NULL ENABLE_TDS,NULL FIXED_DISCOUNT,NULL PACKAGE_CODE,NULL PACKAGE_AMOUNT,
NULL MOBILE_NO2,NULL MOBILE_NO3,NULL EXCISE_REG_NO,NULL LOCK_FLAG,NULL AGE,NULL CARE_OF,NULL FPAN_NO,NULL ENABLE_CREDIT_LIMIT,NULL BILL_TO,NULL SHIP_TO,NULL MODE_OF_PAYMENT 
FROM MR_FIREA02.AMS.AccountGroup WHERE GrpType='A'

INSERT INTO dbo.CUSTOMER_SETUP(CUSTOMER_CODE, CUSTOMER_DESC, NEPALI_NAME, ADDRESS, PAN_NO, PHONE_NO, MOBILE_NO, REMARKS, GROUP_FLAG, MASTER_CODE, PRE_CODE, ACCOUNT_CODE, MEMBERSHIP_CODE, EMAIL_ID, BANK_NAME, BANK_AC_NO, LC_NO, PRICE_LEVEL, BILL_WISE, IS_CASH_CUSTOMER, CUSTOMER_TYPE, CREATED_DATE, CREATED_BY, MODIFY_BY, MODIFY_DATE, ENABLE_COSTENTER, CREDIT_DAYS, CREDIT_LIMIT, CUSTOMER_ID, ENABLE_TDS, FIXED_DISCOUNT, PACKAGE_CODE, PACKAGE_AMOUNT, MOBILE_NO2, MOBILE_NO3, EXCISE_REG_NO, LOCK_FLAG, AGE, CARE_OF, FPAN_NO, ENABLE_CREDIT_LIMIT, BILL_TO, SHIP_TO, MODE_OF_PAYMENT)
SELECT gl.GLID CUSTOMER_CODE,GLName CUSTOMER_DESC,NepaliDesc NEPALI_NAME,NULL ADDRESS,NULL PAN_NO,NULL PHONE_NO,NULL MOBILE_NO, NULL REMARKS,'I' GROUP_FLAG,gl.GrpId MASTER_CODE,NULL PRE_CODE,NULL ACCOUNT_CODE,NULL MEMBERSHIP_CODE,NULL EMAIL_ID,
NULL BANK_NAME,NULL BANK_AC_NO,NULL LC_NO,NULL PRICE_LEVEL,NULL BILL_WISE,NULL IS_CASH_CUSTOMER,NULL CUSTOMER_TYPE,NULL CREATED_DATE,NULL CREATED_BY,NULL MODIFY_BY,NULL MODIFY_DATE,NULL ENABLE_COSTENTER,NULL CREDIT_DAYS,NULL CREDIT_LIMIT,NULL CUSTOMER_ID,NULL ENABLE_TDS,NULL FIXED_DISCOUNT,NULL PACKAGE_CODE,NULL PACKAGE_AMOUNT,
NULL MOBILE_NO2,NULL MOBILE_NO3,NULL EXCISE_REG_NO,NULL LOCK_FLAG,NULL AGE,NULL CARE_OF,NULL FPAN_NO,NULL ENABLE_CREDIT_LIMIT,NULL BILL_TO,NULL SHIP_TO,NULL MODE_OF_PAYMENT 
FROM MR_FIREA02.AMS.GeneralLedger gl WHERE gl.GLType in ('Customer','Cash','Bank')
AND GLID NOT IN (SELECT CUSTOMER_CODE FROM CUSTOMER_SETUP)

INSERT INTO dbo.TRANSACTION_MASTER(TRANSACTION_NO, TRANSACTION_TYPE, TRANSACTION_DATE, REFERENCE_NO, PARTY_CODE, LEDGER, SALESMAN_CODE, TOTAL_QTY, TOTAL_AMOUNT, MODE_OF_PAYMENT, REMARKS, CREATED_DATE, CREATED_BY, CREATED_TIME, PRINT_FLAG, PRINT_COUNT, 
LAST_PRINT_BY, LAST_PRINT_DATE, LAST_PRINT_TIME, CANCEL_FLAG, CANCEL_BY,  CANCEL_DATE, CANCEL_REASAON, FISCAL_YEAR, REF_INVOICE_NO, RETURN_FLAG, EXPORT_FLAG, TENDER_AMOUNT, REFERENCE_TYPE, PRICE_LEVEL, CURRENCY_CODE, EXCHANGE_RATE, NOTE_LIST, PARTY_TYPE,
PARTY_NAME, PARTY_ADDRESS, PARTY_TPIN, S_BATCH_NO, S_LEVEL, S_YEAR, S_ROLL_NO, TABLE_CODE, BILL_FLAG, SMS_FLAG, MODIFY_BY, MODIFY_DATE, FROM_GODOWN, TO_GODOWN, SYNC_WITH_IRD, IS_REALTIME, FILE_NO, VEHICLE_CODE, TRA_DATE, MITI, ONLINE_TRAN_NO, 
VAT_REFUND_AMT, TAKE_AWAY)
SELECT SB_Invoice TRANSACTION_NO,'Sales' TRANSACTION_TYPE,Invoice_Date TRANSACTION_DATE,NULL REFERENCE_NO,sm.Customer_Id PARTY_CODE,3 LEDGER,NULL SALESMAN_CODE,0 TOTAL_QTY,CAST(sm.LN_Amount AS FLOAT) TOTAL_AMOUNT,CASE WHEN sm.Payment_Mode='' THEN 'Cash' ELSE sm.Payment_Mode end MODE_OF_PAYMENT,sm.Remarks REMARKS,CAST(sm.Enter_Date AS DATE) CREATED_DATE,sm.Enter_By CREATED_BY,
SUBSTRING(CONVERT(nvarchar(50),sm.Enter_Date,109),12,15)  CREATED_TIME,'Y' PRINT_FLAG,sm.No_Print PRINT_COUNT,
sm.Printed_By LAST_PRINT_BY,sm.Printed_Date LAST_PRINT_DATE,SUBSTRING(CONVERT(nvarchar(50),sm.Printed_Date,109),12,15) LAST_PRINT_TIME,sm.R_Invoice CANCEL_FLAG,sm.Cancel_By CANCEL_BY,sm.Cancel_Date CANCEL_DATE,sm.Cancel_Remarks CANCEL_REASAON,'2078-79' FISCAL_YEAR,NULL REF_INVOICE_NO,0 RETURN_FLAG,'N' EXPORT_FLAG,CAST( TENDER_AMOUNT AS FLOAT) TENDER_AMOUNT,NULL REFERENCE_TYPE,NULL PRICE_LEVEL,1001 CURRENCY_CODE,1 EXCHANGE_RATE, NULL NOTE_LIST,NULL PARTY_TYPE, 
PARTY_NAME,NULL PARTY_ADDRESS,NULL PARTY_TPIN,NULL S_BATCH_NO,NULL S_LEVEL,NULL S_YEAR,NULL S_ROLL_NO,NULL TABLE_CODE,'N' BILL_FLAG,'N' SMS_FLAG,NULL MODIFY_BY,NULL MODIFY_DATE,NULL FROM_GODOWN,NULL TO_GODOWN,'Y' SYNC_WITH_IRD,'Y' IS_REALTIME,NULL FILE_NO,NULL VEHICLE_CODE,NULL TRA_DATE,sm.Invoice_Miti MITI,NULL ONLINE_TRAN_NO,
NULL VAT_REFUND_AMT,'N' TAKE_AWAY 
FROM MR_FIREA02.AMS.SB_Master sm 
WHERE SB_Invoice NOT IN (SELECT TRANSACTION_NO FROM TRANSACTION_MASTER)


INSERT INTO dbo.TRANSACTION_DETAILS(SERIAL_NO, TRANSACTION_NO, TRANSACTION_TYPE, ITEM_CODE, UNIT_CODE, DECIMAL_PLACES, QUANTITY, RATE, AMOUNT, ITEM_DESCRIPTION, DISCOUNT_PER, DISCOUNT_RATE, FREE_QUANTITY, NON_TAXABLE_AMOUNT, REMARKS, DISPLAY_DISCOUNT, RATE_AFTER_LED_DIS, RATE_AFTER_TAX, RATE_AFTER_VAT, CREATED_DATE, CREATED_BY, MODIFY_BY, MODIFY_DATE, REFERENCE_NO, ALT_QUANTITY, EXCISE_AMOUNT, TSC_NON_APPLICABLE, CANCEL_QUANTITY, TAKE_AWAY)
SELECT ROW_NUMBER() OVER(PARTITION BY SB_Invoice ORDER BY SB_Invoice) SERIAL_NO  , SB_Invoice TRANSACTION_NO,'Sales' TRANSACTION_TYPE,P_Id ITEM_CODE,NULL UNIT_CODE,NULL DECIMAL_PLACES,Qty QUANTITY,Rate RATE,B_Amount AMOUNT,NULL ITEM_DESCRIPTION,PDiscountRate DISCOUNT_PER,PDiscount DISCOUNT_RATE,0 FREE_QUANTITY, 
NULL NON_TAXABLE_AMOUNT,NULL REMARKS,NULL DISPLAY_DISCOUNT,Rate RATE_AFTER_LED_DIS,Rate RATE_AFTER_TAX,Rate RATE_AFTER_VAT,Rate CREATED_DATE,'Admin' CREATED_BY, NULL MODIFY_BY,NUll MODIFY_DATE, NULL REFERENCE_NO,NULL ALT_QUANTITY,0 EXCISE_AMOUNT,NULL TSC_NON_APPLICABLE,NULL CANCEL_QUANTITY,NULL TAKE_AWAY 
FROM MR_FIREA02.AMS.SB_Details
WHERE SB_Invoice NOT IN (SELECT TRANSACTION_NO FROM TRANSACTION_DETAILS)

INSERT INTO   dbo.ITEM_SETUP(ITEM_CODE, ITEM_NAME, NEPALI_NAME, UNIT_CODE, GROUP_FLAG, MASTER_CODE, PRE_CODE, PUR_RATE, SALES_RATE, ITEM_DESCRIPTION, ACCOUNT_CODE, IS_VEHICLE, CHASSIS_NO, ENGINE_NO, COLOR, ASK_VEHICLE_INFO, ALT_UNIT_CODE, MAIN_UNIT_VALUE, ALT_UNIT_VALUE, PRINT_TICKET_DETAILS, BARCODE, RATE_DECIMAL, IMAGE_PATH, NON_TAXABLE, CREATED_BY, CREATED_DATE, MODIFY_BY, MODIFY_DATE, MRP_RATE, ITEM_TYPE, IS_EXCISE_APPLICABLE, EXCISE_AMOUNT, NON_TSC, PART_NO, ASK_AVIATION_INFO, MIN_RATE, ASK_TICKET_INFO, AC_TYPE, LOCK_FLAG, BATCH_ITEM, CUT_MASTER_RATE, SWE_WORKER_RATE, ASK_TAILORING_INFO, PUR_ACCOUNT, TETANT_TYPE, HS_CODE)
SELECT PID ITEM_CODE,PName ITEM_NAME,NepaliDesc NEPALI_NAME,NULL UNIT_CODE,'I' GROUP_FLAG,NULL MASTER_CODE,NULL PRE_CODE,PBuyRate PUR_RATE,PSalesRate SALES_RATE,PName ITEM_DESCRIPTION,PID ACCOUNT_CODE,'N' IS_VEHICLE,NULL CHASSIS_NO, 
NULL ENGINE_NO,NULL COLOR,'N' ASK_VEHICLE_INFO,NULL ALT_UNIT_CODE,NULL MAIN_UNIT_VALUE,NULL ALT_UNIT_VALUE,NULL PRINT_TICKET_DETAILS,BARCODE,'##,##0.00' RATE_DECIMAL,NULL IMAGE_PATH,'Y' NON_TAXABLE,EnterBy CREATED_BY,EnterDate CREATED_DATE,
NULL MODIFY_BY,NULL MODIFY_DATE,PSalesRate MRP_RATE,'NONE' ITEM_TYPE,'N' IS_EXCISE_APPLICABLE,NULL EXCISE_AMOUNT, 'N' NON_TSC,NULL PART_NO,'N' ASK_AVIATION_INFO,NULL MIN_RATE,'N' ASK_TICKET_INFO,NULL AC_TYPE,'N' LOCK_FLAG,'N' BATCH_ITEM,NULL CUT_MASTER_RATE,NULL SWE_WORKER_RATE,NULL ASK_TAILORING_INFO, 
NULL PUR_ACCOUNT,'N' TETANT_TYPE,NULL HS_CODE 
FROM MR_FIREA02.AMS.Product 
WHERE PID NOT IN (SELECT ITEM_CODE FROM ITEM_SETUP)

INSERT INTO dbo.TRANSACTION_SETUP_LEDGER(SERIAL_NO, TRANSACTION_TYPE, LEDGER_CODE, PERCENTAGE, LEDGER_TYPE, BASE_ON_DISPLAY_DISCOUNT, CREATED_DATE, CREATED_BY, MODIFY_BY, MODIFY_DATE)
SELECT ST_ID,'Sales',1,ST_Rate,ST_Name,'N',Cast(EnterDate as date),'MrSolution',NULL,NULL FROM MR_FIREIC01.AMS.ST_Term

INSERT INTO dbo.TRANSACTION_LEDGER(SERIAL_NO, TRANSACTION_NO, TRANSACTION_TYPE, LEDGER_CODE, PERCENTAGE, AMOUNT, LEDGER_TYPE, CREATED_DATE, CREATED_BY, MODIFY_BY, MODIFY_DATE)
SELECT ROW_NUMBER() OVER(PARTITION BY SB_VNo ORDER BY SB_VNo) SERIAL_NO,SB_VNo TRANSACTION_NO,'Sales' TRANSACTION_TYPE,sbt.ST_Id LEDGER_CODE,Rate PERCENTAGE, AMOUNT,st.ST_Name LEDGER_TYPE,st.EnterDate CREATED_DATE,'MrSolution' CREATED_BY,NULL MODIFY_BY,NULL MODIFY_DATE FROM MR_FIREA02.AMS.SB_Term sbt
INNER JOIN MR_FIREA02.AMS.ST_Term st ON st.ST_ID = sbt.ST_Id
WHERE sbt.Term_Type <> 'BT' AND SB_VNo NOT IN (SELECT TRANSACTION_NO FROM TRANSACTION_LEDGER)
