INSERT INTO AMS.AccountGroup(GrpId, NepaliDesc, GrpName, GrpCode, Schedule, PrimaryGrp, GrpType, Branch_ID, Company_Id, Status, EnterBy, EnterDate, PrimaryGroupId, IsDefault, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT ROW_NUMBER() OVER (ORDER BY ag.GrpDesc) GrpId, ag.GrpDesc NepaliDesc, ag.GrpDesc GrpName, GrpCode, ag.GrpSchedule Schedule, CASE WHEN ag.PrimaryGrp IN ('Liabilities', 'Assets') THEN 'BS' ELSE 'PL' END PrimaryGrp, SUBSTRING(ag.PrimaryGrp, 1, 1) GrpType, 1 Branch_ID, NULL Company_Id, 1 Status, 'MrSolution' EnterBy, GETDATE() EnterDate, NULL PrimaryGroupId, 0 IsDefault, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion
FROM PART798001.dbo.AccountGroup ag
WHERE ag.GrpDesc NOT IN(SELECT GrpName FROM AMS.AccountGroup);

INSERT INTO AMS.Currency(CId, NepaliDesc, CName, CCode, CRate, Branch_ID, Company_Id, Status, IsDefault, EnterBy, EnterDate, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT ROW_NUMBER() OVER (ORDER BY c.CurrDesc) CId, c.CurrDesc NepaliDesc, c.CurrDesc CName, c.CurrCode CCode, c.CurrRate CRate, 1 Branch_ID, NULL Company_Id, 1 Status, 0 IsDefault, 'MrSolution' EnterBy, GETDATE() EnterDate, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion
FROM PART798001.dbo.currency c
WHERE c.CurrDesc NOT IN(SELECT CName FROM AMS.Currency);

INSERT INTO AMS.GeneralLedger(GLID, NepaliDesc, GLName, GLCode, ACCode, GLType, GrpId, PrimaryGroupId, SubGrpId, PrimarySubGroupId, PanNo, AreaId, AgentId, CurrId, CrDays, CrLimit, CrTYpe, IntRate, GLAddress, PhoneNo, LandLineNo, OwnerName, OwnerNumber, Scheme, Email, Branch_ID, Company_Id, EnterBy, EnterDate, Status, IsDefault, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT ROW_NUMBER() OVER (ORDER BY gl.GlDesc) GLID, gl.GlDesc NepaliDesc, gl.GlDesc GLName, gl.GlCode GLCode, gl.AccountingCode ACCode, CASE WHEN gl.Catagory='Customer/Vendor' THEN 'Both'
                                                                                                                                        WHEN gl.Catagory='Cash Book' THEN 'Cash'
                                                                                                                                        WHEN gl.Catagory='Bank Book' THEN 'Bank' ELSE gl.Catagory END GLType, ag.GrpId, ag.PrimaryGroupId, NULL SubGrpId, NULL PrimarySubGroupId, gl.PanNo, NULL AreaId, NULL AgentId, 1 CurrId, 0 CrDays, 0 CrLimit, 'I' CrTYpe, 0 IntRate, gl.AddressI GLAddress, gl.Mobile PhoneNo, NULL LandLineNo, NULL OwnerName, NULL OwnerNumber, NULL Scheme, NULL Email, 1 Branch_ID, NULL Company_Id, 'MrSolution' EnterBy, GETDATE() EnterDate, 1 Status, 0 IsDefault, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion
FROM PART798001.dbo.GeneralLedger gl
     LEFT OUTER JOIN AMS.AccountGroup ag ON ag.GrpCode=gl.GrpCode;

INSERT INTO AMS.ProductUnit(UID, NepaliDesc, UnitName, UnitCode, Branch_ID, Company_Id, EnterBy, EnterDate, Status, IsDefault, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT ROW_NUMBER() OVER (ORDER BY pu.UnitCode) UID, pu.UnitCode NepaliDesc, pu.UnitCode UnitName, pu.UnitCode UnitCode, 1 Branch_ID, NULL Company_Id, 'MrSolution' EnterBy, GETDATE() EnterDate, 1 Status, 0 IsDefault, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion
FROM PART798001.dbo.Product pu
WHERE pu.UnitCode NOT IN(SELECT UnitCode FROM AMS.ProductUnit)AND ISNULL(pu.UnitCode, '')<>''
GROUP BY pu.UnitCode;

INSERT INTO AMS.ProductUnit(UID, NepaliDesc, UnitName, UnitCode, Branch_ID, Company_Id, EnterBy, EnterDate, Status, IsDefault, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT 6+ROW_NUMBER() OVER (ORDER BY pu.AltUnitCode) UID, pu.AltUnitCode NepaliDesc, pu.AltUnitCode UnitName, pu.AltUnitCode UnitCode, 1 Branch_ID, NULL Company_Id, 'MrSolution' EnterBy, GETDATE() EnterDate, 1 Status, 0 IsDefault, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion
FROM PART798001.dbo.Product pu
WHERE pu.AltUnitCode NOT IN(SELECT UnitCode FROM AMS.ProductUnit)AND ISNULL(pu.AltUnitCode, '')<>''
GROUP BY pu.AltUnitCode;

INSERT INTO AMS.Product(PID, NepaliDesc, PName, PAlias, PShortName, PType, PCategory, PUnit, PAltUnit, PQtyConv, PAltConv, PValTech, PSerialno, PSizewise, PBatchwise, PVehicleWise, PublicationWise, PBuyRate, AltSalesRate, PSalesRate, PMargin1, TradeRate, PMargin2, PMRP, PGrpId, PSubGrpId, PTax, PMin, PMax, CmpId, CmpId1, CmpId2, CmpId3, Branch_Id, CmpUnit_Id, PPL, PPR, PSL, PSR, PL_Opening, PL_Closing, BS_Closing, PImage, EnterBy, EnterDate, IsDefault, Status, ChasisNo, EngineNo, VHModel, VHColor, VHNumber, BeforeBuyRate, BeforeSalesRate, Barcode, Barcode1, Barcode2, Barcode3, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT p.Id PID, p.PDesc NepaliDesc, p.PDesc PName, p.PDesc PAlias, p.PCode PShortName, p.Catagory PType, p.ValuationMethod PCategory, ISNULL(pu.UID, 3) PUnit, au.UID PAltUnit, p.AltQty PQtyConv, p.Qty PAltConv, 'FIFO' PValTech, 0 PSerialno, 0 PSizewise, 0 PBatchwise, 0 PVehicleWise, 0 PublicationWise, p.BuyRate PBuyRate, ISNULL(p.AltSalesRate, 0) AltSalesRate, p.SalesRate PSalesRate, p.Margin PMargin1, p.TradeRate TradeRate, 0 PMargin2, 0 PMRP, NULL PGrpId, NULL PSubGrpId, p.Vat PTax, 0 PMin, 0 PMax, NULL CmpId, NULL CmpId1, NULL CmpId2, NULL CmpId3, 1 Branch_Id, NULL CmpUnit_Id, NULL PPL, NULL PPR, NULL PSL, NULL PSR, NULL PL_Opening, NULL PL_Closing, NULL BS_Closing, NULL PImage, 'MrSolution' EnterBy, GETDATE() EnterDate, 0 IsDefault, 1 Status, NULL ChasisNo, NULL EngineNo, NULL VHModel, NULL VHColor, NULL VHNumber, 0 BeforeBuyRate, 0 BeforeSalesRate, NULL Barcode, NULL Barcode1, NULL Barcode2, NULL Barcode3, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion
FROM PART798001.dbo.Product p
     LEFT OUTER JOIN AMS.ProductUnit pu ON pu.UnitCode=p.UnitCode
     LEFT OUTER JOIN AMS.ProductUnit au ON au.UnitCode=p.AltUnitCode
WHERE Id NOT IN(SELECT PID FROM AMS.Product);

INSERT INTO AMS.SB_Master(SB_Invoice, Invoice_Date, Invoice_Miti, Invoice_Time, PB_Vno, Vno_Date, Vno_Miti, Customer_Id, PartyLedgerId, Party_Name, Vat_No, Contact_Person, Mobile_No, Address, ChqNo, ChqDate, ChqMiti, Invoice_Type, Invoice_Mode, Payment_Mode, DueDays, DueDate, Agent_Id, Subledger_Id, SO_Invoice, SO_Date, SC_Invoice, SC_Date, Cls1, Cls2, Cls3, Cls4, CounterId, Cur_Id, Cur_Rate, B_Amount, T_Amount, N_Amount, LN_Amount, V_Amount, Tbl_Amount, Tender_Amount, Return_Amount, Action_Type, In_Words, Remarks, R_Invoice, Cancel_By, Cancel_Date, Cancel_Remarks, Is_Printed, No_Print, Printed_By, Printed_Date, Audit_Lock, Enter_By, Enter_Date, Reconcile_By, Reconcile_Date, Auth_By, Auth_Date, Cleared_By, Cleared_Date, DoctorId, PatientId, HDepartmentId, MShipId, TableId, CBranch_Id, CUnit_Id, FiscalYearId, IsAPIPosted, IsRealtime, PAttachment1, PAttachment2, PAttachment3, PAttachment4, PAttachment5, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion, IsSynced)
SELECT sm.VNo SB_Invoice, sm.VDate Invoice_Date, sm.VMiti Invoice_Miti, sm.VTime Invoice_Time, sm.RefNo PB_Vno, sm.RefDate Vno_Date, sm.RefMiti Vno_Miti, gl.GLID Customer_Id, NULL PartyLedgerId, sm.PartyName Party_Name, sm.VatNo Vat_No, NULL Contact_Person, NULL Mobile_No, NULL Address, NULL ChqNo, NULL ChqDate, NULL ChqMiti, 'LOCAL' Invoice_Type, 'NORMAL' Invoice_Mode, CASE WHEN gl.GLType IN ('Cash', 'Bank') THEN 'CASH' ELSE 'CREDIT' END Payment_Mode, 0 DueDays, NULL DueDate, NULL Agent_Id, NULL Subledger_Id, NULL SO_Invoice, NULL SO_Date, NULL SC_Invoice, NULL SC_Date, NULL Cls1, NULL Cls2, NULL Cls3, NULL Cls4, NULL CounterId, 1 Cur_Id, 1 Cur_Rate, sm.BasicAmt B_Amount, sm.TermAmt T_Amount, sm.NetAmt N_Amount, sm.NetAmt LN_Amount, 0 V_Amount, 0 Tbl_Amount, 0 Tender_Amount, 0 Return_Amount, sm.EntryType Action_Type, sm.NetAmt In_Words, sm.Remarks, 0 R_Invoice, NULL Cancel_By, NULL Cancel_Date, NULL Cancel_Remarks, 0 Is_Printed, 0 No_Print, NULL Printed_By, NULL Printed_Date, 0 Audit_Lock, 'MrSolution' Enter_By, GETDATE() Enter_Date, NULL Reconcile_By, NULL Reconcile_Date, NULL Auth_By, NULL Auth_Date, NULL Cleared_By, NULL Cleared_Date, NULL DoctorId, NULL PatientId, NULL HDepartmentId, NULL MShipId, NULL TableId, 1 CBranch_Id, NULL CUnit_Id, 13 FiscalYearId, NULL IsAPIPosted, NULL IsRealtime, NULL PAttachment1, NULL PAttachment2, NULL PAttachment3, NULL PAttachment4, NULL PAttachment5, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion, 0 IsSynced
FROM PART798001.dbo.SalesInvoiceMaster sm
     LEFT OUTER JOIN AMS.GeneralLedger gl ON gl.GLCode=sm.GLCode
WHERE sm.VNo NOT IN(SELECT SB_Invoice FROM AMS.SB_Master);

INSERT INTO AMS.SB_Details(SB_Invoice, Invoice_SNo, P_Id, Gdn_Id, Alt_Qty, Alt_UnitId, Qty, Unit_Id, Rate, B_Amount, T_Amount, N_Amount, AltStock_Qty, Stock_Qty, Narration, SO_Invoice, SO_Sno, SC_Invoice, SC_SNo, Tax_Amount, V_Amount, V_Rate, Free_Unit_Id, Free_Qty, StockFree_Qty, ExtraFree_Unit_Id, ExtraFree_Qty, ExtraStockFree_Qty, T_Product, S_Ledger, SR_Ledger, SZ1, SZ2, SZ3, SZ4, SZ5, SZ6, SZ7, SZ8, SZ9, SZ10, Serial_No, Batch_No, Exp_Date, Manu_Date, MaterialPost, PDiscountRate, PDiscount, BDiscountRate, BDiscount, ServiceChargeRate, ServiceCharge, SyncBaseId, SyncGlobalId, SyncOriginId, SyncCreatedOn, SyncLastPatchedOn, SyncRowVersion)
SELECT sd.VNo SB_Invoice, sd.SNo Invoice_SNo, p.PID P_Id, NULL Gdn_Id, sd.AltQty Alt_Qty, au.UID Alt_UnitId, sd.Qty, pu.UID Unit_Id, sd.CurrRate Rate, sd.CurrAmt B_Amount, sd.TermAmt T_Amount, sd.LocalAmt N_Amount, sd.AltQty AltStock_Qty, sd.Qty Stock_Qty, sd.Narration, NULL SO_Invoice, NULL SO_Sno, NULL SC_Invoice, NULL SC_SNo, 0 Tax_Amount, 0 V_Amount, 0 V_Rate, NULL Free_Unit_Id, 0 Free_Qty, 0 StockFree_Qty, NULL ExtraFree_Unit_Id, 0 ExtraFree_Qty, 0 ExtraStockFree_Qty, 0 T_Product, NULL S_Ledger, NULL SR_Ledger, NULL SZ1, NULL SZ2, NULL SZ3, NULL SZ4, NULL SZ5, NULL SZ6, NULL SZ7, NULL SZ8, NULL SZ9, NULL SZ10, NULL Serial_No, NULL Batch_No, NULL Exp_Date, NULL Manu_Date, 'N' MaterialPost, 0 PDiscountRate, 0 PDiscount, 0 BDiscountRate, 0 BDiscount, 0 ServiceChargeRate, 0 ServiceCharge, NULL SyncBaseId, NULL SyncGlobalId, NULL SyncOriginId, NULL SyncCreatedOn, NULL SyncLastPatchedOn, 1 SyncRowVersion
FROM PART798001.dbo.SalesInvoiceDetails sd
     LEFT OUTER JOIN AMS.Product p ON p.PShortName=sd.PCode
     LEFT OUTER JOIN AMS.ProductUnit pu ON pu.UnitName=sd.MUnit
     LEFT OUTER JOIN AMS.ProductUnit au ON au.UnitCode=sd.AUnit
WHERE sd.VNo NOT IN(SELECT SB_Invoice FROM AMS.SB_Details);


UPDATE AMS.SB_Master SET PB_Vno = NULL