USE master;
IF NOT EXISTS (SELECT s.name FROM sys.schemas s WHERE s.name='CRM')BEGIN
    DECLARE @AMS NVARCHAR(MAX);
    SET @AMS='CREATE SCHEMA CRM AUTHORIZATION dbo;';
    EXEC sys.sp_executesql @AMS;
END;
IF OBJECT_ID('CRM.UserRoleGroup') IS NULL BEGIN
    CREATE TABLE [CRM].[UserRoleGroup] ([GroupId] [INT] IDENTITY(1, 1) NOT NULL,
    [GroupDesc] [NVARCHAR](50) NOT NULL,
    [EnterBy] [NVARCHAR](50) NOT NULL,
    [EnterDate] [DATETIME] NOT NULL,
    [IsActive] [BIT] NOT NULL,
    [IsDefault] [BIT] NOT NULL,
    CONSTRAINT [PK_UserRoleGroup] PRIMARY KEY NONCLUSTERED([GroupId] ASC)WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS= ON, ALLOW_PAGE_LOCKS=ON)ON [PRIMARY])ON [PRIMARY];
    CREATE UNIQUE CLUSTERED INDEX [IX_UserRoleGroup] ON [CRM].[UserRoleGroup]([GroupDesc] ASC)
    WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, SORT_IN_TEMPDB=OFF, IGNORE_DUP_KEY=OFF, DROP_EXISTING=OFF, ONLINE=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON);
END;
IF OBJECT_ID('CRM.LoginUserInfo') IS NULL BEGIN
    CREATE TABLE [CRM].[LoginUserInfo] ([UserId] [INT] IDENTITY(1, 1) NOT NULL,
    [UserName] [NVARCHAR](50) NOT NULL,
    [UserFullName] [NVARCHAR](100) NOT NULL,
    [PhoneNo] [NVARCHAR](50) NULL,
    [EmailId] [NVARCHAR](50) NULL,
    [UserAddress] [NVARCHAR](50) NULL,
    [Password] [NVARCHAR](MAX) NULL,
    [LoginTime] [TIME](7) NULL,
    [LogOutTime] [TIME](7) NULL,
    [GroupId] [INT] NOT NULL,
    [IsActive] [BIT] NOT NULL,
    [IsDefault] [BIT] NOT NULL,
    CONSTRAINT [PK_LoginUserInfo] PRIMARY KEY CLUSTERED([UserId] ASC)WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS= ON, ALLOW_PAGE_LOCKS=ON)ON [PRIMARY])ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
    ALTER TABLE [CRM].[LoginUserInfo] WITH CHECK
    ADD CONSTRAINT [FK_LoginUserInfo_UserRoleGroup] FOREIGN KEY([GroupId])REFERENCES [CRM].[UserRoleGroup]([GroupId]);
    ALTER TABLE [CRM].[LoginUserInfo] CHECK CONSTRAINT [FK_LoginUserInfo_UserRoleGroup];
    CREATE UNIQUE NONCLUSTERED INDEX [IX_LoginUserInfo] ON [CRM].[LoginUserInfo]([UserName] ASC)
    WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, SORT_IN_TEMPDB=OFF, IGNORE_DUP_KEY=OFF, DROP_EXISTING=OFF, ONLINE=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON);
END;
IF OBJECT_ID('CRM.CompanyInfo') IS NULL BEGIN
    CREATE TABLE [CRM].[CompanyInfo] ([CompanyId] [INT] IDENTITY(1, 1) NOT NULL,
    [CompanyInitial] [NVARCHAR](15) NOT NULL,
    [CompanyName] [NVARCHAR](100) NOT NULL,
    [PrintingDesc] [NVARCHAR](100) NOT NULL,
    [SaveLocation] [NVARCHAR](255) NOT NULL,
    [IsActive] [BIT] NULL,
    CONSTRAINT [PK_CompanyInfo] PRIMARY KEY CLUSTERED([CompanyId] ASC)WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS= ON, ALLOW_PAGE_LOCKS=ON)ON [PRIMARY])ON [PRIMARY];
    CREATE UNIQUE NONCLUSTERED INDEX [IX_CompanyInfo] ON [CRM].[CompanyInfo]([CompanyName] ASC)
    WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, SORT_IN_TEMPDB=OFF, IGNORE_DUP_KEY=OFF, DROP_EXISTING=OFF, ONLINE=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON);
    CREATE UNIQUE NONCLUSTERED INDEX [IX_CompanyInfo_Initial]
    ON [CRM].[CompanyInfo]([CompanyInitial] ASC)
    WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, SORT_IN_TEMPDB=OFF, IGNORE_DUP_KEY=OFF, DROP_EXISTING=OFF, ONLINE=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON);
END;
