

IF (EXISTS (  SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS  ifc WHERE TABLE_NAME = 'SystemSetting' and ifc.COLUMN_NAME = 'AmountFormat' AND ifc.DATA_TYPE = 'float'))
BEGIN
   ALTER TABLE AMS.SystemSetting ALTER COLUMN AmountFormat NVARCHAR(10);
END;

IF (EXISTS (  SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS  ifc WHERE TABLE_NAME = 'SystemSetting' and ifc.COLUMN_NAME = 'QtyFormat' AND ifc.DATA_TYPE = 'float'))
BEGIN
   ALTER TABLE AMS.SystemSetting ALTER COLUMN QtyFormat NVARCHAR(10);
END;

IF (EXISTS (  SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS  ifc WHERE TABLE_NAME = 'SystemSetting' and ifc.COLUMN_NAME = 'RateFormat' AND ifc.DATA_TYPE = 'float'))
BEGIN
   ALTER TABLE AMS.SystemSetting ALTER COLUMN RateFormat NVARCHAR(10);
END;
IF (EXISTS (  SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS  ifc WHERE TABLE_NAME = 'SystemSetting' and ifc.COLUMN_NAME = 'CurrencyFormatF' AND ifc.DATA_TYPE = 'float'))
BEGIN
   ALTER TABLE AMS.SystemSetting ALTER COLUMN CurrencyFormatF NVARCHAR(10);
END;
IF (EXISTS (  SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS  ifc WHERE TABLE_NAME = 'SystemSetting' and ifc.COLUMN_NAME = 'CurrencyRate' AND ifc.DATA_TYPE = 'float'))
BEGIN
   ALTER TABLE AMS.SystemSetting ALTER COLUMN CurrencyRate DECIMAL(18,6);
END;