
---------------  Account ledgers
ALTER TABLE AMS.GeneralLedger ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.GeneralLedger ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.GeneralLedger ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.GeneralLedger ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
ALTER TABLE AMS.GeneralLedger ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_GeneralLedger_SyncGlobalId ON AMS.GeneralLedger ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_GeneralLedger_SyncBaseId ON AMS.GeneralLedger ( SyncBaseId )
GO 


ALTER TABLE AMS.AccountGroup ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.AccountGroup ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.AccountGroup ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.AccountGroup ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
ALTER TABLE AMS.AccountGroup ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_AccountGroup_SyncGlobalId ON AMS.AccountGroup ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_AccountGroup_SyncBaseId ON AMS.AccountGroup ( SyncBaseId )
GO 


ALTER TABLE AMS.AccountSubGroup ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.AccountSubGroup ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.AccountSubGroup ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.AccountSubGroup ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.AccountSubGroup ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_AccountSubGroup_SyncGlobalId ON AMS.AccountSubGroup ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_AccountSubGroup_SyncBaseId ON AMS.AccountSubGroup ( SyncBaseId )
GO 


ALTER TABLE AMS.JuniorAgent ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.JuniorAgent ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.JuniorAgent ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.JuniorAgent ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.JuniorAgent ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_JuniorAgent_SyncGlobalId ON AMS.JuniorAgent ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_JuniorAgent_SyncBaseId ON AMS.JuniorAgent ( SyncBaseId )
GO 


ALTER TABLE AMS.Currency ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.Currency ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.Currency ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.Currency ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.Currency ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_Currency_SyncGlobalId ON AMS.Currency ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_Currency_SyncBaseId ON AMS.Currency ( SyncBaseId )
GO



--------------------   Products
ALTER TABLE AMS.Product ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.Product ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.Product ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.Product ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.Product ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_Product_SyncGlobalId ON AMS.Product ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_Product_SyncBaseId ON AMS.Product ( SyncBaseId )
GO 


ALTER TABLE AMS.ProductUnit ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductUnit ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductUnit ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductUnit ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.ProductUnit ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_ProductUnit_SyncGlobalId ON AMS.ProductUnit ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_ProductUnit_SyncBaseId ON AMS.ProductUnit ( SyncBaseId )
GO 



ALTER TABLE AMS.ProductGroup ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductGroup ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductGroup ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductGroup ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.ProductGroup ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_ProductGroup_SyncGlobalId ON AMS.ProductGroup ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_ProductGroup_SyncBaseId ON AMS.ProductGroup ( SyncBaseId )
GO 


ALTER TABLE AMS.ProductSubGroup ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductSubGroup ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductSubGroup ALTER COLUMN SyncBaseId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.ProductSubGroup ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.ProductSubGroup ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_ProductSubGroup_SyncGlobalId ON AMS.ProductSubGroup ( SyncGlobalId )
CREATE UNIQUE NONCLUSTERED INDEX IX_ProductSubGroup_SyncBaseId ON AMS.ProductSubGroup ( SyncBaseId )
GO 



-------------- Sales
ALTER TABLE AMS.SB_Master ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SB_Master ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SB_Master ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.SB_Master ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_SB_Master_SyncGlobalId ON AMS.SB_Master ( SyncGlobalId )
GO 


ALTER TABLE AMS.SB_Details ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SB_Details ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SB_Details ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.SB_Details ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_SB_Details_SyncGlobalId ON AMS.SB_Details ( SyncGlobalId )
GO 


ALTER TABLE AMS.SB_Term ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SB_Term ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SB_Term ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.SB_Term ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_SB_Term_SyncGlobalId ON AMS.SB_Term ( SyncGlobalId )
GO 



----------------- Sales  returns
ALTER TABLE AMS.SR_Master ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SR_Master ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SR_Master ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.SR_Master ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_SR_Master_GlobalId ON ams.SR_Master ( SyncGlobalId ) 
GO 

ALTER TABLE AMS.SR_Details ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SR_Details ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SR_Details ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.SR_Details ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_SR_Details_GlobalId ON ams.SR_Details ( SyncGlobalId ) 
GO 

ALTER TABLE AMS.SR_Term ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SR_Term ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.SR_Term ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.SR_Term ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_SR_Term_GlobalId ON ams.SR_Term ( SyncGlobalId ) 
GO 



-----------------  Purchase
ALTER TABLE AMS.PB_Master ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PB_Master ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PB_Master ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.PB_Master ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_PB_Master_GlobalId ON AMS.PB_Master ( SyncGlobalId )
GO 

ALTER TABLE AMS.PB_Details ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PB_Details ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PB_Details ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.PB_Details ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_PB_Details_GlobalId ON AMS.PB_Details ( SyncGlobalId )
GO 

ALTER TABLE AMS.PB_Term ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PB_Term ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PB_Term ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.PB_Term ALTER COLUMN SyncRowVersion SMALLINT NOT NULL 
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_PB_Term_GlobalId ON AMS.PB_Term ( SyncGlobalId )
GO 



--------------- Purchase returns
ALTER TABLE AMS.PR_Master ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PR_Master ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PR_Master ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.PR_Master ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_PR_Master_GlobalId ON AMS.PR_Master ( SyncGlobalId )
GO 

ALTER TABLE AMS.PR_Details ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PR_Details ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PR_Details ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.PR_Details ALTER COLUMN SyncRowVersion SMALLINT NOT NULL
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_PB_Details_GlobalId ON AMS.PR_Details ( SyncGlobalId )
GO 


ALTER TABLE AMS.PR_Term ALTER COLUMN SyncGlobalId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PR_Term ALTER COLUMN SyncOriginId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE AMS.PR_Term ALTER COLUMN SyncCreatedOn DATETIME NOT NULL
ALTER TABLE AMS.PR_Term ALTER COLUMN SyncRowVersion SMALLINT NOT NULL 
GO 
CREATE UNIQUE NONCLUSTERED INDEX IX_PR_Term_GlobalId ON AMS.PR_Term ( SyncGlobalId )
GO 










